/** Auto-generated by scripts/generate-promoted-exact-patterns.ts — do not edit. */
import type { EffectDefinition } from "../dsl/types";
import type { ExtractedEffect, WikiEffectSegment } from "./types";
import { noteEffectIdFromBody, slugifyEffectId } from "./metaMaps";

type PatternMatch = {
  pattern: string;
  test: (body: string) => boolean;
  build: (
    body: string,
    segment: WikiEffectSegment,
    trigger: EffectDefinition["trigger"],
  ) => Omit<ExtractedEffect, "segmentIndex" | "needsFallback">;
};

function normalizeBody(body: string): string {
  return body.replace(/\s+/g, "").trim();
}

function triggerFromBody(
  body: string,
  fallback: EffectDefinition["trigger"],
): EffectDefinition["trigger"] {
  if (/バトルエリアに出たとき/.test(body)) return { type: "enter_battle" };
  if (/ラッシュしたとき|ラッシュするとき/.test(body)) return { type: "on_rush" };
  if (/アタックしたとき|アタックするとき/.test(body)) return { type: "on_attack" };
  if (/ストライクしたとき|ストライクして/.test(body)) return { type: "on_strike" };
  if (/撃破されて捨札になったとき/.test(body)) return { type: "on_destroy" };
  if (/敵軍ターン中/.test(body) || /にある間/.test(body)) return { type: "while_in_field" };
  return fallback;
}

function grantPrFx(
  cardId: string,
  effectId: string,
  body: string,
  segment: WikiEffectSegment,
  trigger: EffectDefinition["trigger"],
  matchedPattern: string,
  optional?: boolean,
): Omit<ExtractedEffect, "segmentIndex" | "needsFallback"> {
  return {
    id: segment.name ? slugifyEffectId(segment.name) : noteEffectIdFromBody(body),
    name: segment.name,
    text: body,
    trigger: triggerFromBody(body, trigger),
    optional: optional ?? /してもよい|してよい|選んでもよい/.test(body),
    effects: [
      {
        type: "grant_keyword",
        keyword: `pr_fx::${cardId}::${effectId}`,
        duration: /にある間/.test(body) ? "permanent" : "turn",
      },
    ],
    matchedPattern,
  };
}

const PR_TEXT_0 = `自軍パワーゾーンからダメージ以外のカードを5枚選び捨札にしてもよい。そうしたとき、このターン、このユニットは次の能力を得る⇒「SP3」`;

export const PR_EXACT_PATTERNS: PatternMatch[] = [
  {
    pattern: "pr_exact_PR_005_justice_flasher",
    test: (body) => normalizeBody(body) === normalizeBody(PR_TEXT_0),
    build: (body, segment, trigger) =>
      grantPrFx("PR-005", "justice_flasher", body, segment, trigger, "pr_exact_PR_005_justice_flasher"),
  },
];
