/** Auto-generated by scripts/generate-rk-exact-patterns.ts — do not edit. */
import type { EffectDefinition } from "../dsl/types";
import type { ExtractedEffect, WikiEffectSegment } from "./types";
import { noteEffectIdFromBody, slugifyEffectId } from "./metaMaps";

type PatternMatch = {
  pattern: string;
  test: (body: string) => boolean;
  build: (
    body: string,
    segment: WikiEffectSegment,
    trigger: EffectDefinition["trigger"],
  ) => Omit<ExtractedEffect, "segmentIndex" | "needsFallback">;
};

function normalizeBody(body: string): string {
  return body.replace(/\s+/g, "").trim();
}

function triggerFromBody(
  body: string,
  fallback: EffectDefinition["trigger"],
): EffectDefinition["trigger"] {
  if (/バトルエリアに出たとき/.test(body)) return { type: "enter_battle" };
  if (/ラッシュしたとき|ラッシュするとき/.test(body)) return { type: "on_rush" };
  if (/アタックしたとき|アタックするとき/.test(body)) return { type: "on_attack" };
  if (/ストライクしたとき|ストライクして/.test(body)) return { type: "on_strike" };
  if (/撃破されて捨札になったとき/.test(body)) return { type: "on_destroy" };
  if (/敵軍ターン中/.test(body) || /にある間/.test(body)) return { type: "while_in_field" };
  return fallback;
}

function grantRkFx(
  cardId: string,
  effectId: string,
  body: string,
  segment: WikiEffectSegment,
  trigger: EffectDefinition["trigger"],
  matchedPattern: string,
  optional?: boolean,
): Omit<ExtractedEffect, "segmentIndex" | "needsFallback"> {
  return {
    id: segment.name ? slugifyEffectId(segment.name) : noteEffectIdFromBody(body),
    name: segment.name,
    text: body,
    trigger: triggerFromBody(body, trigger),
    optional: optional ?? /してもよい|してよい|選んでもよい/.test(body),
    effects: [
      {
        type: "grant_keyword",
        keyword: `rk_fx::${cardId}::${effectId}`,
        duration: /にある間/.test(body) ? "permanent" : "turn",
      },
    ],
    matchedPattern,
  };
}

const RK_TEXT_0 = `次の効果を、相手、自分の順に行う。 自分自身の山札の上から3枚をオモテにして相手に見せる。その中から特徴「車両」を持つMユニットのカードをすべて自分自身のパワーゾーンに置き、それ以外は好きな順で自分自身の山札の下に戻す。`;
const RK_TEXT_1 = `これが自軍エリアにある間、自軍バトルエリアにある特徴「戦闘員」を持つ自軍SユニットのBPは、自軍バトルエリアにある特徴「戦闘員」を持つ自軍Sユニットの本来のBPをすべて「＋」した値になる。また、特徴「戦闘員」を持つ自軍Sユニットは、BP3000のとき「SP1」になる。`;
const RK_TEXT_2 = `これが自軍バトルエリアにある間、敵軍ターン中、敵軍バトルエリアの特徴「忍者」を持たないユニットは、アタックするとき、バトルの前にBP-3000される。（BP0以下になったユニットは撃破される）この効果は重複しない。`;
const RK_TEXT_3 = `これにライドしているユニットは、敵軍ターン中、リリース状態の自軍コマンド1つにつきBP+1000される。`;
const RK_TEXT_4 = `敵軍ターン中、これが撃破されて捨札になったとき、このユニットカードを自軍コマンドゾーンにホールド状態で置いてもよい。（置けなければこの効果は発動できない）`;
const RK_TEXT_5 = `これにライドしているSユニットは次の能力を得る⇒ これが自軍ラッシュエリアにある間、相手にストライクされたとき、これをバトルエリアに出し、ストライクしてきた敵軍ユニットとバトルしてもよい。そうしたとき、そのストライクは無効になる。`;
const RK_TEXT_6 = `｢マグナギガ｣からコンビネーションしたとき発動できる⇒ホールド状態のSユニットをすべて撃破する。その後、Sユニットをすべてホールドする。`;
const RK_TEXT_7 = `これがライドされたままなら、このビークルからコンビネーションするSユニットは次の能力を得る⇒ナンバーにＲＣを持っていれば、ライドオフしなくてもその効果を発動できる。`;
const RK_TEXT_8 = `これが自軍ラッシュエリアにある間、敵軍ターン中、「クレインオルフェノク」以外の特徴「オルフェノク」を持つ自軍ユニットが撃破されて捨札になるたび、敵軍Sユニットを1体選び撃破してもよい。`;
const RK_TEXT_9 = `これが自軍バトルエリアにある間、相手は次の制限を受ける⇒自分自身のターン中、アタックや効果の対象として対戦相手の「スネークオルフェノク」を一度も選んでいなければ、特徴「仮面ライダー」を持つ対戦相手のユニットと「スネークオルフェノク」以外の特徴「オルフェノク」を持つ対戦相手のユニットは選べない。`;
const RK_TEXT_10 = `自分の手札を3枚選び、相手に見せてもよい。そうしたとき、敵軍Sユニットを1体選びホールドする。その後、見せたカードの必要パワーの数字が番号順（例：0、1、2や3、4、5など）に揃うなら、敵軍Sユニットを1体選び撃破する。`;
const RK_TEXT_11 = `自分の手札を3枚選び、相手に見せてもよい。そうしたとき、見せたカードがすべて、BPの下三桁が500の追加条件を持たないユニットカードなら、そのカードをすべて自軍ラッシュエリアに出す。`;
const RK_TEXT_12 = `これにライドしたユニットがある間、自分の手札からカードが1枚捨札に置かれるたび、次の効果を発動できる⇒ホールド状態の敵軍ユニットを1体選び撃破する。`;
const RK_TEXT_13 = `敵軍Lユニットを1体選び、自軍山札の上から7枚までオモテにしてもよい。そうしたとき、オモテにしたユニットカードのBPの合計が、選んだLユニットのBP以上なら、選んだLユニットを撃破する。その後、オモテにしたカードはすべて捨札になる。`;
const RK_TEXT_14 = `これが自軍エリアにある間、敵軍山札がシャッフルされたとき、これがホールド状態ならリリースしてもよい。`;
const RK_TEXT_15 = `数字を1つ宣言してもよい。そうしたとき、自軍山札の下から1枚ひいてオモテにする。オモテにしたカードの必要パワーの数字が、宣言した数字と同じなら、自分の手札に加え、それ以外なら山札の下に戻す。`;
const RK_TEXT_16 = `これをラッシュしたとき、自軍パワーゾーンのオモテ向きのカードを見て、その枚数以下の必要パワーの数値を持つ追加条件を持たない敵軍ユニットを1体選び、持ち主のパワーゾーンに送ってもよい。`;
const RK_TEXT_17 = `これが撃破されて捨札になったとき、相手は自分自身の捨札から特徴「女」を持つユニットカードを1枚選び、自分自身のラッシュエリアに出してもよい。相手がそうしなかったとき、自軍捨札から「ウカワーム」以外の特徴「女」を持つユニットカードを1枚選び、自分の手札に戻してもよい。`;
const RK_TEXT_18 = `相手は自分自身のラッシュエリアからユニットを1体選び、可能ならバトルエリアに出す。`;
const RK_TEXT_19 = `これがストライクしたとき、次の効果を、自分が三回まで好きな回数行った後で、相手も同じ回数行う。 自分自身の山札の上から1枚をオモテにする。そして、オモテにしたカードの必要パワーの数値を見て、その数字と同じ必要パワーの数字を持つ自分自身のユニットがあれば、その中から1体選び撃破する。そうして撃破したなら、オモテにしたカードは捨札になり、撃破しなかったら手札に加える。`;
const RK_TEXT_20 = `これをラッシュしたとき、次の効果を、相手、自分の順に行う⇒自分自身の山札からオペレーションカードを1枚選び、相手に見せてから手札に加えてもよい。そうしたとき、自分自身の山札をシャッフルする。 ・このテキストは公式ＨＰで読み替えが推奨されています。修正後は以下。`;
const RK_TEXT_21 = `これをラッシュしたとき、次の効果を、相手、自分の順に行う⇒自分自身の山札を見てもよい。そうしたとき、その中からオペレーションカードを1枚選び、相手に見せてから手札に加える。その後、山札をシャッフルする。`;
const RK_TEXT_22 = `このユニットからコンビネーションするSP1/4のSユニットは、次の能力を得る⇒自軍ターン中、「SP1」になる。`;
const RK_TEXT_23 = `自軍ターン中、これがバトルエリアに出たとき、敵軍バトルエリアからMユニットを1体選び、敵軍ラッシュエリアに戻してもよい。そうしたとき、戻したユニットが特徴「メカ」を持っていなければ、持ち主のパワーゾーンへ送る。`;
const RK_TEXT_24 = `これが自軍バトルエリアにある間、このユニットから「デンライナーゴウカ、デンライナーイスルギ、デンライナーレッコウ」の順にコンビネーションしたとき、本来のBPが3000以下の敵軍ユニットをすべて撃破する。`;
const RK_TEXT_25 = `これをラッシュしたとき、敵軍パワーゾーンのダメージ以外のカードの枚数を数えてから、そのカードをすべて捨札にしてもよい。そうしたとき、数えた枚数と同じ枚数になるまで敵軍捨札からカードを選び、敵軍パワーゾーンにオモテ向きで置く。`;
const RK_TEXT_26 = `これが自軍ラッシュエリアにある間、自分がターンを終えるとき、敵軍バトルエリアから特徴「車両」を持つユニットを1体選んでもよい。そうしたとき、次の相手のターン、相手はスタートフェイズにバトルエリアのユニットをラッシュエリアに戻すとき、選ばれたユニットをラッシュエリアに戻すことはできない。`;
const RK_TEXT_27 = `これをラッシュしたとき、敵軍Sユニットか、敵軍Mユニットを1体選んでもよい。そうしたとき、選んだユニットがSユニットなら、このターン、そのユニットはBP500になり、そのBPより高いBPになる効果はすべて無効になる。選んだユニットがMユニットなら、このターン、そのユニットはSユニットになる。`;
const RK_TEXT_28 = `自軍ターン中、これがバトルエリアに出たとき、自軍バトルエリアから特徴「車両」を持つMユニットを1体選び、自軍パワーゾーンに送ってもよい。また、これがラッシュエリアに戻るとき、自軍パワーゾーンのオモテ向きのカードから、特徴「車両」を持つMユニットのカードを1枚選び、自軍ラッシュエリアに出してもよい。`;
const RK_TEXT_29 = `これが自軍バトルエリアからラッシュエリアに戻るとき、自軍常駐置き場からカードを1枚選び、自分の手札に加えてもよい。ただし、ウラ向きのカードはウラ向きのまま選ぶ。`;
const RK_TEXT_30 = `必要パワーの数字に「－」のある敵軍Sユニットを1体選び撃破してもよい。`;
const RK_TEXT_31 = `これが自軍エリアにある間、追加条件を持たない敵軍Sユニットがラッシュされたとき、そのユニットの必要パワーの数字と同じ必要パワーの数字を持つDAのユニットカードを自分の手札から1枚選び、ラッシュエリアに出してもよい。ただし、DAの自軍コマンドを1つホールドすること。そうしたとき、ラッシュされた敵軍ユニットを撃破する。`;
const RK_TEXT_32 = `敵軍捨札からユニットカードを1枚選んでもよい。そうしたとき、選んだカードと同じカード名の敵軍ユニットを1体選び、撃破する。`;
const RK_TEXT_33 = `敵軍ターン中、これが撃破されて捨札になったとき次の効果を発動できる⇒自軍パワーゾーンからダメージになっているカードを1枚選び、オモテにする。このとき、オモテにしたカードが「ジーク」なら、そのカードを捨札にしてこの効果をもう一度発動できる。`;
const RK_TEXT_34 = `BPの下三桁が500の敵軍Sユニットを1体選び撃破する。（この効果は「サイドバッシャーBM」からコンビネーションするときはナンバーに関係なく発動する）`;
const RK_TEXT_35 = `自軍ターン中、これがバトルエリアに出たとき、パワーゾーンでオモテ向きになっている「モモタロス」「ウラタロス」「キンタロス」「リュウタロス」のカードを捨札にしたときに発動する効果は、捨札にせずに発動できる。`;
const RK_TEXT_36 = `本来の特徴に「ミラーライダー」を持つ自軍ユニットを1体選ぶ。このターン、選んだユニットは、指定されたユニットからコンビネーションしたときに発動できる効果名を持つ効果を、指定されたユニットのかわりに、本来の特徴に「ミラーモンスター」を持つユニットからコンビネーションすれば、その効果を発動できる。`;
const RK_TEXT_37 = `自軍Sユニットを選ぶ。そして、このカードを自軍ラッシュエリアに置き、選んだユニットをこのカードに重ねる。このカードに重ねたユニットは、敵軍ターン中、リリース状態の自軍コマンド1つにつきBP+1000される。重ねたユニットがユニットでなくなるとき、このカードは捨札になる。`;
const RK_TEXT_38 = `これが自軍エリアにある間、自分も相手も次の制限を受ける⇒自分自身のラッシュフェイズを終えるとき、そのターン中にラッシュした自分自身のSユニットをホールドするかしないかを選ぶ。ホールドしないことを選んだとき、そのユニットはそのターン中、バトルエリアに出られない。`;
const RK_TEXT_39 = `自軍ターン中、これがバトルエリアに出たとき、ライド中の敵軍Sユニットを1体選んでもよい。そうしたとき、選んだユニットの持つカテゴリと、選んだユニットがライドしているビークルの持つカテゴリが違うなら、そのビークルを捨札にした後で、選んだユニットを撃破する。`;
const RK_TEXT_40 = `敵軍ラッシュエリアからライドされていないSビークルを1体選んでもよい。そうしたとき、ライドしていない敵軍Sユニットを1体選び、選んだビークルにライドさせる。`;
const RK_TEXT_41 = `自軍ターン中、これがバトルエリアに出たとき、WBを持つ自軍コマンドを1つホールドしてもよい。そうしたとき、このターン、これは次の能力を得る⇒SP1/5になり、これとバトルしたSユニットは、バトルに勝っても撃破される。`;
const RK_TEXT_42 = `これにライドしているユニットがアタックするとき、敵軍ユニットのBPをカードに表記された本来の値としてバトルする。`;
const RK_TEXT_43 = `これは、アタックしてバトルに勝つたび、追加でアタックできる。ただし、これはバトルを終えるたび、このターン、BP-1000される。（BP0以下になったユニットは撃破される）`;
const RK_TEXT_44 = `これが自軍エリアにある間、これがホールド状態になったとき、自軍常駐置き場からカードを1枚選び捨札にしてもよい（ウラ向きのカードはウラ向きのまま選ぶ）。そうしたとき、これをリリースする。`;
const RK_TEXT_45 = `自軍ターン中、これがバトルエリアに出たとき、敵軍山札の下から1枚ひいてオモテにしてもよい。オモテにしたカードがＲＣを持つユニットカードなら、このターン、これはSP1になり、オモテにしたカードのRCの効果をこのユニットの効果として発動する。その後、オモテにしたカードは持ち主の山札の下に戻す。`;
const RK_TEXT_46 = `これがアタックするとき、自軍コマンドを好きな数ホールドしてもよい。そうしたとき、このターン、これはホールドしたコマンド1つにつきBP+1000される。`;
const RK_TEXT_47 = `自軍ターン中、これがバトルエリアに出たとき、敵軍バトルエリアから、追加条件に「自軍合体ユニットを捨札にする」と表記されていないDAを持つ敵軍Lユニットを1体選び、持ち主のパワーゾーンにダメージにして置いてもよい。`;
const RK_TEXT_48 = `これが自軍エリアにある間、敵軍ターン中、自軍Sユニットがアタックされたとき、次の効果を発動できる⇒自分の手札の必要パワーに「－」を持つユニットカードから、アタックされたSユニットが追加条件で指定されているカードを1枚選び、自軍バトルエリアに出してもよい（このとき出したユニットの効果は発動しない）。そうしたとき、アタックされたユニットを捨札にして、かわりにバトルエリアに出したユニットでバトルする。`;
const RK_TEXT_49 = `自軍ターン中、これがバトルエリアに出たとき、自軍コマンドを2つまで選び、リリースしてもよい。`;
const RK_TEXT_50 = `これをラッシュしたとき、次の効果を発動できる⇒自軍山札をシャッフルした後、その上から2枚をオモテにする。そして自軍山札を見て、ユニットカードを1枚選びラッシュエリアに出してもよい。ただし選べるカードは、カテゴリがオモテにした1枚目と同じで、必要パワーの数字がオモテにした2枚目と同じカードとする。その後、オモテにしたカードは山札に戻してシャッフルする。`;
const RK_TEXT_51 = `これをラッシュしたとき、これをホールドしてもよい。そうしたとき、このターン、これはSP1になる。`;
const RK_TEXT_52 = `これをラッシュしたとき、レジストを持つ敵軍Sユニットを1体選んでもよい。そうしたとき、そのユニットとこのユニットでバトルする。`;
const RK_TEXT_53 = `これをラッシュしたとき、カード1枚につきBP1000として、相手の手札の枚数分のBPを計算し、そのBP以下の敵軍ユニットを1体選び撃破してもよい。`;
const RK_TEXT_54 = `ホールド状態の自軍ユニットの数を数えて、その数以下の必要パワーの数字を持つSユニットを敵軍バトルエリアから1体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければこの効果は発動できない。`;
const RK_TEXT_55 = `これが自軍エリアにある間、これがホールド状態からリリース状態になったとき、これ以外の自軍Sユニットを1体選びホールドしても良い。そうしたとき、敵軍Sユニットを1体選び撃破する。`;
const RK_TEXT_56 = `自軍ターン中、これがバトルエリアに出たとき、レジストを持つユニットを1体選んでもよい。そうしたとき、相手は選ばれたユニットを撃破するか、1点ダメージを受けるか選ぶ。`;
const RK_TEXT_57 = `これが自軍バトルエリアにある間、特徴「女」を持つユニットは次の能力を得る⇒レジスト (これがバトルで撃破されたとき、捨札にするかわりにこれをホールドしてその場に留めてもよい)`;
const RK_TEXT_58 = `特徴「レイヨウ型」を持つユニットからコンビネーションしたとき発動できる⇒レジストを持たない敵軍Sユニットを、特徴「レイヨウ型」を持つユニットの数まで選びホールドする。`;
const RK_TEXT_59 = `これが自軍エリアにある間、次の効果を発動する⇒「オメガゼール」以外の特徴「レイヨウ型」を持つ自軍ユニットは「これはコマンドを1つホールドしなければバトルエリアに出られない」と書かれていても、そのテキストは無効になる。また相手は特徴「レイヨウ型」を持つユニットを撃破したとき、1枚ドローしてもよい。`;
const RK_TEXT_60 = `自軍ターン中、これがバトルエリアに出たとき、ライド中の敵軍Sユニットを、特徴「レイヨウ型」を持つ自軍ユニットの数まで選んでもよい。そうしたとき、選んだユニットをライドオフさせる。`;
const RK_TEXT_61 = `これをラッシュしたとき、次の効果を、相手、自分の順に行う⇒自分自身のユニットを1体選ぶ。そして、自分自身の選んだユニットの持っていないカテゴリを持つ自分自身のSユニットを1体選び撃破する。`;
const RK_TEXT_62 = `自軍ターン中、これがアタックしてバトルに勝ったとき、常駐している自軍オペレーションに重ねたカードがあれば、その中から1枚選び、山札の下に戻してもよい（ウラ向きのカードはウラ向きのまま選ぶ）。そうしたとき、これをラッシュエリアに戻す。`;
const RK_TEXT_63 = `これはラッシュしたときバトルエリアに出してもよい。そうしたとき、これをラッシュするためにホールドしたコマンドの必要パワーの数字を見て、その数字と同じ必要パワーの数字を持つ敵軍Sユニット1体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければ捨札にする。このとき、これはアタックもストライクもできない。`;
const RK_TEXT_64 = `これが自軍エリアにある間、自分も相手も次の制限を受ける⇒アタックを1度でも行った場合、そのターン中はアタックすることができない。また、ストライクを1度でも行った場合、そのターン中はストライクすることができない。`;
const RK_TEXT_65 = `これが自軍ラッシュエリアにある間、効果に「ラッシュしたとき」とある敵軍ユニットが手札からラッシュされたとき、その効果を実行する前に、これをバトルエリアに出してもよい。そうしたとき、その効果は無効になる。その後、そのユニットとこのユニットでバトルする。`;
const RK_TEXT_66 = `自軍ターン中、これがバトルエリアに出たとき、自軍バトルエリアのSユニットをすべてホールドしてもよい。そうしたとき、ホールドしたユニットの数以下の必要パワーの数字を持つ敵軍ユニットをすべて撃破する。`;
const RK_TEXT_67 = `自軍ターン中、これがバトルエリアに出たとき、自分の手札を3枚選び、相手に見せてもよい。そうしたとき、見せたカードの必要パワーの数字が番号順（例：0、1、2や3、4、5など）に揃うなら、敵軍Sユニットを1体選び撃破する。`;
const RK_TEXT_68 = `自軍ターン中、これがバトルエリアに出たとき、自分の手札を2枚選び、相手に見せてもよい。そうしたとき、見せたカードの持つカテゴリがすべて同じなら、必要パワーを満たしていない敵軍ユニットを1体選び撃破する。そうして撃破したユニットの本来のSPが1以上なら、そのSPと同じ数だけ、相手にダメージを与える。`;
const RK_TEXT_69 = `ホールド状態の敵軍Sユニットを2体選んでもよい。そうしたとき、選んだ2体の持つカテゴリが違うなら、相手はそのどちらか1体を選び撃破する。`;
const RK_TEXT_70 = `敵軍バトルエリアのSユニットを2体選んでもよい。そうしたとき、相手は次のようにする⇒選ばれたユニットのうち1体を撃破する。その後、もう1体をホールドする。`;
const RK_TEXT_71 = `これは敵軍ラッシュエリアのレジストを持つユニットにアタックできる。`;
const RK_TEXT_72 = `自軍ターン中、これがバトルエリアに出たとき、自軍ラッシュエリアから、特徴｢アンデッド｣を持つ自軍ユニットを1体選んでも良い。そうしたとき、選んだユニットは、このターン「SP1」になり、ターンを終えるとき撃破される。`;
const RK_TEXT_73 = `これが自軍エリアにある間、自軍ラッシュフェイズ中、自軍｢アルビローチ｣をラッシュしたとき次の効果を発動できる⇒自軍「アルビローチ」の数を数えて、その数と同じ必要パワーの数字を持つ敵軍ユニットを1体選び撃破する。`;
const RK_TEXT_74 = `自分の手札からオペレーションカードを1枚選び、捨札にしてもよい。そうしたとき、このターン、これは次の能力を得る⇒「SP1」になり、このターンを終えるときホールド状態なら、リリースしてもよい。`;
const RK_TEXT_75 = `MAを持つコマンドを2つホールドしてもよい。そうしたとき、このターン、これは次の能力を得る⇒「SP1」になり、このターンを終えるときホールド状態なら、リリースしてもよい。`;
const RK_TEXT_76 = `自軍山札の上から3枚をオモテにしてもよい。そうしたとき、敵軍山札の上から3枚をオモテにする。そして、オモテにしたカードの中から「SP1」を持つSユニットのカードをすべて捨札にし、それ以外を持ち主の山札に戻してシャッフルする。（この効果は、特徴「猛士」を持つユニットからコンビネーションする時、ナンバーに関係なく発動する）`;
const RK_TEXT_77 = `これが自軍エリアにある間、敵軍バトルエリアのSユニットは、「これは敵軍ターン中、SP1以上のユニットとバトルしたときバトルに勝っても撃破される」と書かれているかのように扱う。`;
const RK_TEXT_78 = `自軍と敵軍の常駐置き場にあるカードの枚数を数えて、その枚数以下の必要パワーの数字を持つ敵軍ユニットを1体選び、持ち主のパワーゾーンにダメージにして置いてもよい。`;
const RK_TEXT_79 = `自分の手札より相手の手札の枚数が多ければ、相手の手札を見ないで1枚選んでもよい。 そうしたとき、選んだカードを持ち主の山札の上に戻す。`;
const RK_TEXT_80 = `敵軍バトルエリアからユニットを1体選んでもよい。そうしたとき、敵軍パワーゾーンのオモテ向きのカードから、選んだユニットの持つ特徴をすべて持つユニットカードを1枚選び、ウラ向きにしてダメージにする。`;
const RK_TEXT_81 = `敵軍ユニットの下にオモテ向きで重ねたオペレーションカードを1体選んでもよい。そうしたとき、選んだカードを持ち主の山札に戻してシャッフルする。`;
const RK_TEXT_82 = `自分がターンを終えるとき、これをリリースするか、ホールドしてもよい。 これはホールド状態のとき、アタックもストライクもすることができず、敵軍ユニットにアタックされない。 ・このテキストはクロスギャザーコンプリートブックでエラッタが示されています。修正後は以下。`;
const RK_TEXT_83 = `自分がターンを終えるとき、このユニットをリリースするか、ホールドしてもよい。 これはホールド状態のとき、アタックもストライクもすることができず、敵軍ユニットにアタックされない。`;
const RK_TEXT_84 = `自軍ターン中、これがバトルエリアに出たとき、次の効果を発動できる⇒相手は1枚ドローしてから、自分自身の手札からカードを1枚選び、自分自身のパワーゾーンに置く。その後、相手の置いたカードの必要パワーの数字を見て、その数字以下の必要パワーの数字を持つ敵軍ユニットを1体選び、持ち主のパワーゾーンに送る。`;
const RK_TEXT_85 = `自軍ターン中、これがバトルエリアに出たとき、次の効果を発動できる⇒敵軍バトルエリアからSユニットを1体選び、敵軍ラッシュエリアに戻してもよい。そうしたとき、敵軍ラッシュエリアに、戻したユニットの持つカテゴリを持たないユニットがあれば1体選び、戻したユニットとバトルさせる。`;
const RK_TEXT_86 = `敵軍Sユニットの数が自軍Sユニットの数より3体以上多いとき、敵軍Sユニットを1体選び、持ち主のパワーゾーンに送る。`;
const RK_TEXT_87 = `これが自軍エリアにある間、敵軍ラッシュフェイズ中、特徴「警察」を持つ敵軍ユニットがラッシュされたとき、次の効果を発動できる⇒自分の手札からDAを持つBP3000以下のSユニットのカードを1枚選び、ラッシュエリアに出してもよい。ただし、追加条件は満たすこと。`;
const RK_TEXT_88 = `自軍ターン中、これがバトルエリアに出たとき、このユニットをホールドしてもよい。そうしたとき、常駐しているオペレーションを1つ選び、選んだオペレーションを持ち主の山札に戻してシャッフルする。`;
const RK_TEXT_89 = `これが自軍エリアにある間、特徴「仮面ライダー」を持つユニットがユニットを撃破して捨札にしたとき、その特徴「仮面ライダー」を持つユニットの持ち主は1枚ドローしてもよい。`;
const RK_TEXT_90 = `自軍ターン中、これがバトルエリアに出たとき、本来の特徴に「イマジン」を持つ自軍バトルエリアのユニットの数を数えてもよい。そうしたとき、その数以下の必要パワーを持つSユニットを、本来の特徴に「イマジン」を持つ自軍バトルエリアのユニットの数まで選び、持ち主のパワーゾーンに送る。`;
const RK_TEXT_91 = `これが撃破されて捨札になったとき、自軍捨札から「モモタロス」のカードを1枚選び、自軍ラッシュエリアに出してもよい。`;
const RK_TEXT_92 = `自軍ターン中、これがバトルエリアに出たとき、このユニットをホールドしてもよい。そうしたとき、敵軍バトルエリアから相手の手札の枚数以下の必要パワーの数字を持つSユニットを1体選び、持ち主のパワーゾーンにダメージにして置く。`;
const RK_TEXT_93 = `これが自軍エリアにある間、次の効果を発動する⇒特徴「警察」を持つユニットは、可能なら毎ターンバトルエリアに出る。`;
const RK_TEXT_94 = `このユニットを捨札にして、次の効果を発動してもよい⇒敵軍バトルエリアから必要パワーの数字が3以下のユニットを1体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければ敵軍コマンドを1つ選び、捨札にしてから置く。`;
const RK_TEXT_95 = `自軍ターン中、これがバトルエリアに出たとき、敵軍バトルエリアからSPが空欄でないSユニットを1体選んでもよい。そうしたとき、このターン、選んだユニットはBP－1000される。（BP0以下になったユニットは撃破される）`;
const RK_TEXT_96 = `ライドされている「カブトロー」からこのビークルがコンビネーションしている間、これにライドしているユニットは次の能力を得る⇒敵軍ユニットにアタックされない。`;
const RK_TEXT_97 = `このターン、特徴「女」を持つ敵軍ユニットを1体以上撃破して捨札にしたなら、自分がターンを終えるとき、相手に1点ダメージを与えてもよい。`;
const RK_TEXT_98 = `これが自軍エリアにある間、自分がターンを終えるとき、自軍捨札からカードを1枚選び、これの下にウラ向きで重ねてもよい。これがユニットでなくなるとき、この下に重ねたウラ向きのカードをすべて捨札にする。そうして捨札にするとき、それが敵軍ターン中なら、捨札にするカード1枚につき、そのカードの必要パワーの数字と同じ必要パワーの数字を持つ敵軍Sユニットを1体選び撃破してもよい。`;
const RK_TEXT_99 = `敵軍捨て札からオペレーションカードを1枚選び、持ち主のパワーゾーンにダメージにして置いてもよい。`;
const RK_TEXT_100 = `このユニットは、ホールド状態のとき敵軍ユニットにアタックされない。`;
const RK_TEXT_101 = `自軍ターン中、これがバトルエリアに出たとき、これにライドしているユニットのBP以下のBPを持つユニットを、相手は自分自身のSユニットの中から1体選び、自分自身の山札の下に戻す。`;
const RK_TEXT_102 = `自軍ターン中、これがバトルエリアに出たとき、これがライドされていれば、敵軍常駐の上に重ねたカードの上から1枚選び、持ち主の山札の下に戻してもよい。`;
const RK_TEXT_103 = `敵軍ラッシュエリアのユニットを、BPの合計が3000以下になるように選び撃破してもよい。ただし、選べるユニットの数は、特徴「メカ」を持つ自軍ユニットの数までとする。`;
const RK_TEXT_104 = `このユニットとバトルして撃破された敵軍ユニットは、レジストを発動する事ができない。`;
const RK_TEXT_105 = `これが自軍バトルエリアにある間、すべてのバトルは本来のBPで行う。`;
const RK_TEXT_106 = `これがバトルで敵軍ユニットを撃破したとき、これが撃破した敵軍ユニットのBP以下のBPを持つ、自分と相手のバトルエリアのSユニットをすべて撃破する。`;
const RK_TEXT_107 = `これが自軍エリアにある間、敵軍ユニットがＮＣまたはＲＣの効果を発動させたとき、その効果を実行する前に、自分の手札からカードを1枚選び自軍山札の上に戻してもよい。そうしたとき、そのNCまたはRCの効果を無効にする。`;
const RK_TEXT_108 = `自軍ラッシュエリアのSユニットを1体以上選び手札に戻してもよい。そうしたとき、相手は次のどちらかを選び行う⇒◎手札に戻したユニットの数まで自分自身のユニットを可能な限り選び撃破する。◎自分自身のユニットを1体選びダメージにする。`;
const RK_TEXT_109 = `自軍ターン中、これがバトルエリアに出たとき、次の効果を発動できる⇒自軍山札の上から2枚を見て、そのカードを山札の上か下にそれぞれ好きな順で戻す。`;
const RK_TEXT_110 = `自軍ターン中、これがバトルエリアに出たとき、敵軍パワーゾーンのダメージ以外のカードから、Sユニットのカードを1枚選び、敵軍ラッシュエリアに出してもよい。そうしたとき、相手は自分自身の山札の上から1枚ひいて、自分自身のパワーゾーンに置いてもよい。`;
const RK_TEXT_111 = `自軍ターン中、これがバトルエリアに出たとき、相手の手札を見ないで1枚選んでもよい。そうしたとき、選んだカードをお互いに見て、それがSユニットのカードだったなら、敵軍ラッシュエリアに出す。このとき、可能ならそのユニットをホールドする。その後、相手は1枚ドローする。`;
const RK_TEXT_112 = `これをラッシュしたとき、この追加条件で捨札にしたカードを見て、DAを持つカードをすべてこれの下に好きな順でウラ向きに重ねる。このとき、ウラ向きに4枚重ねなかったなら、「ン・ダグバ・ゼバ」以外の自軍ユニットをすべて捨札にする。また、これがユニットでなくなるとき、これにウラ向きで重ねたカードをウラ向きのまま1枚選び捨札にして、これをその場に留める。`;
const RK_TEXT_113 = `自軍捨札から特徴「アドベントカード」を持つカードを2枚まで選んでもよい。そうしたとき、敵軍バトルエリアからSユニットを好きな数選び撃破してもよい。ただし、選んだユニットの特徴の数の合計が、捨札から選んだカードの必要パワーの数字の合計以下になるように選ぶこと。`;
const RK_TEXT_114 = `これがライドされているか、これが自軍バトルエリアにある間、敵軍バトルエリアのSユニットは特徴を持たないユニットとして扱い、特徴を追加されない。`;
const RK_TEXT_115 = `これにライドしている特徴「サバイブ」を持つユニットは「SP1」になる。`;
const RK_TEXT_116 = `これが自軍エリアにある間、敵軍ターン中、特徴「ミラーライダー」を持つ自軍ユニットが撃破されて捨札になったとき、自分も相手も次のようにする⇒撃破されたユニットの必要パワーの数字と同じ必要パワーの数字を持つSユニットのカードを、自分自身のコマンドゾーンから1枚選び捨札にする。`;
const RK_TEXT_117 = `「バイオグリーザ」からコンビネーションしたとき発動できる⇒敵軍バトルエリアから、BP4000以下のSユニットを1体選び撃破する。そうしたとき、撃破したユニットのBPがこのユニットのBPよりも低ければ、相手は自分自身のコマンドゾーンからカードを1枚選び捨札にする。`;
const RK_TEXT_118 = `これをラッシュしたとき、次の効果を自分、相手の順に行う⇒自分自身のパワーゾーンのカード枚数を見て、その枚数よりも必要パワーの数字が大きい自分自身のユニットをすべて撃破する。`;
const RK_TEXT_119 = `これをラッシュしたとき、敵軍コマンドゾーンから、モーフを持つユニットカードを1枚選び捨札にしてもよい。`;
const RK_TEXT_120 = `このターン、敵軍バトルエリアのすべてのSユニットはBP-500される。（BP0以下になったユニットは撃破される）`;
const RK_TEXT_121 = `自軍ターン中、これがバトルエリアに出たとき、敵軍ビークルが2体以上あれば、ライドされていない敵軍Sビークルか、ライドされていない敵軍Mビークルを1体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければこの効果は発動できない。`;
const RK_TEXT_122 = `自軍ターン中、これがバトルエリアに出たとき、相手に1枚ドローさせる。その後、相手は追加条件を持たない自分自身のSユニットを1体選び撃破する。`;
const RK_TEXT_123 = `自軍ターン中、これがバトルエリアに出たとき、敵軍バトルエリアからSユニットを1体選び、持ち主のパワーゾーンにダメージにして置いてもよい。`;
const RK_TEXT_124 = `敵軍ターン中、これが撃破されて捨札になったとき、次の効果を発動できる⇒自軍山札を見て「クロコダイルオルフェノク格闘態」のカードを1枚選び、相手に見せてから自分の手札に加えてもよい。その後、自軍山札をシャッフルする。`;
const RK_TEXT_125 = `これが自軍バトルエリアにある間、敵軍ターン中、次の効果を発揮できる⇒敵軍ユニットがラッシュされたとき、自軍コマンドを1つホールドしてもよい。そうしたとき、相手は自分自身のコマンドを1つホールドするかしないかを選ぶ。ホールドしないことを選んだとき、そのユニットはそのターン中、バトルエリアに出られない。`;
const RK_TEXT_126 = `このターン、これは自軍パワーゾーンのカード枚数が敵軍パワーゾーンのカード枚数よりも1枚多いごとにBP+1000され、BP5000以上のとき「SP1」になる。`;
const RK_TEXT_127 = `敵軍バトルエリアのユニットを、必要パワーの数字の合計が2になるまで好きな数選んでもよい（自軍Sユニットが「仮面ライダーキックホッパー」と「仮面ライダーパンチホッパー」だけなら、4になるまで好きな数選んでもよい）。そうしたとき、選んだユニットを持ち主のパワーゾーンに送る。`;
const RK_TEXT_128 = `自軍ターン中、これがバトルエリアに出たとき、敵軍バトルエリアのユニットがSユニット1体だけなら、そのユニットを持ち主のパワーゾーンに送ってもよい。`;
const RK_TEXT_129 = `自軍ターン中、これがバトルエリアに出たとき、敵軍コマンドを3つリリースしてもよい。そうしたとき、このターン、これは「SP1」になる。`;
const RK_TEXT_130 = `これにライドしているユニットは、特徴「加速」を持たないSユニットにアタックされない。`;
const RK_TEXT_131 = `ライドされている「カブトエクステンダー」からこのビークルがコンビネーションしたとき、次の効果を発動できる⇒本来のBPが8000以下の敵軍ユニットを1体選び、持ち主のパワーゾーンに送る。`;
const RK_TEXT_132 = `これが自軍エリアにある間、特徴「ワーム」または特徴「怪人」を持つ敵軍ユニットはアタックもストライクも出来ない。また、敵軍ターン中、これが撃破されたとき、特徴「ワーム」または特徴「怪人」を持つすべてのユニットを撃破する。`;
const RK_TEXT_133 = `これが自分の手札にある間、敵軍ターン中、特徴「男」または「女」を持つ自軍ユニットが撃破されて捨札になったとき、捨札になったユニットカード1枚につき、自分の手札から「ワームサナギ体」のカードを1枚選び、自軍ラッシュエリアに出してもよい。`;
const RK_TEXT_134 = `ホールド状態の敵軍Ｓユニットを1体選び、持ち主のパワーゾーンに送っても良い。`;
const RK_TEXT_135 = `敵軍コマンドを2つ、1つずつ順番に選びリリースしてもよい。そうしたとき、本来のカテゴリが1つ目にリリースしたコマンドと同じで、本来の必要パワーが2つ目にリリースしたコマンドと同じ敵軍Sユニットをすべて撃破する。`;
const RK_TEXT_136 = `自軍ターン中、これがバトルエリアに出たとき、本来のBPがこのユニットのBP以下のユニットを、自軍と敵軍のユニットからそれぞれ1体ずつ選び、持ち主のパワーゾーンに送る。`;
const RK_TEXT_137 = `敵軍ラッシュエリアから、必要パワーの数字が3以下のユニットを1体選び撃破する。`;
const RK_TEXT_138 = `自軍パワーゾーンのオモテ向きのカードから、特徴「獣」を持つユニットカードを1枚選び自分の手札に戻してもよい。そうしたとき、敵軍ラッシュエリアから本来のBPが3000以下のユニットを1体選び撃破する。`;
const RK_TEXT_139 = `自軍パワーゾーンのオモテ向きのカードから、必要パワーを満たしている特徴「女」を持つSユニットのカードを1枚選び、自軍ラッシュエリアに出してもよい（ただし追加条件は満たすこと）。この効果でラッシュしたユニットは、このターン、バトルエリアに出られない。`;
const RK_TEXT_140 = `次の相手ターン、バトルエリアに出た敵軍Sユニットは、可能ならこれにアタックする。`;
const RK_TEXT_141 = `これが自軍エリアにある間、特徴「魔皇力」を持つ自軍Sユニットは、次の能力を得る⇒`;
const RK_TEXT_142 = `これが自軍エリアにある間、モーフの効果で自軍コマンドゾーンか自軍パワーゾーンのオモテ向きのカードからユニットカードを選ぶとき、DAを持つ自軍コマンドを2つ（自軍エリアに｢キャッスルドラン｣があれば1つ）ホールドしてもよい。そうしたとき、かわりに自軍捨札から選んでもよい。`;
const RK_TEXT_143 = `自軍ターン中、これがバトルエリアに出たとき、敵軍バトルエリアから敵軍ダメージの点数以下の必要パワーの数字を持つSユニットを1体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければ捨札にする。そうしたとき、このユニットがリリース状態ならホールドし、ホールド状態なら撃破する。`;
const RK_TEXT_144 = `敵軍バトルエリアから、BPが本来のBPでないユニットを１体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければ捨札にする。`;
const RK_TEXT_145 = `自軍ターン中、これがバトルエリアに出たとき、このユニットをホールドしてもよい。そうしたとき、敵軍Sユニットの下に重ねたカード（ユニットやビークルとして扱われているものも含む。ウラ向きのカードはウラ向きのまま選ぶ）を1枚選び、持ち主のパワーゾーンにダメージにして置く。`;
const RK_TEXT_146 = `自分がターンを終えるとき、これにライドしているユニットがホールド状態ならば、そのユニットをリリースしてもよい。`;
const RK_TEXT_147 = `これにライドしているユニットがBP4000以上の敵軍Sユニットを撃破して捨札にしたとき、捨札にしたそのユニットカードを持ち主のパワーゾーンにダメージにして置いてもよい。`;
const RK_TEXT_148 = `自軍ターン中、これがバトルエリアに出たとき、自軍コマンドゾーンからカードを1枚選び、自軍山札の上か下に戻してもよい。そうしたとき、戻したカードの必要パワーの数字と同じ必要パワーの数字を持つSユニットを敵軍バトルエリアから1体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければ捨札にする。`;
const RK_TEXT_149 = `自軍ラッシュフェイズ中、このユニットを捨札にして次の効果を発動できる⇒自軍山札を見て「仮面ライダーキバGF」のカードを1枚か、自軍捨札に「バッシャー獣人態」と「ドッガ怪人態」があれば「仮面ライダーキバDGBKF」のカードを1枚選び、自軍ラッシュエリアに出してもよい。その後、山札をシャッフルする。`;
const RK_TEXT_150 = `自軍ラッシュフェイズ中、このユニットを捨札にして次の効果を発動できる⇒自軍山札を見て「仮面ライダーキバBF」のカードを1枚か、自軍捨札に「ガルル獣人態」と「ドッガ怪人態」があれば「仮面ライダーキバDGBKF」のカードを1枚選び、自軍ラッシュエリアに出してもよい。その後、山札をシャッフルする。`;
const RK_TEXT_151 = `自軍ラッシュフェイズ中、このユニットを捨札にして次の効果を発動できる⇒自軍山札を見て「仮面ライダーキバDF」のカードを1枚か、自軍捨札に「ガルル獣人態」と「バッシャー獣人態」があれば「仮面ライダーキバDGBKF」のカードを1枚選び、自軍ラッシュエリアに出してもよい。その後、山札をシャッフルする。`;
const RK_TEXT_152 = `自軍ターン中、これがバトルエリアに出たとき、BPの一番低いユニットを１体選び撃破する。ただし、BPの一番低いユニットが自軍と敵軍にある場合は、自軍ユニットの中から選ぶこと。`;
const RK_TEXT_153 = `自軍ターン中、これがバトルエリアに出たとき、本来の特徴に「怪人」を持つ敵軍ユニットを1体選び、持ち主のパワーゾーンにダメージにして置いてもよい。`;

export const RK_EXACT_PATTERNS: PatternMatch[] = [
  {
    pattern: "rk_exact_RK_089_fx_unknown_e4b997",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_0),
    build: (body, segment, trigger) =>
      grantRkFx("RK-089", "fx_unknown_e4b997", body, segment, trigger, "rk_exact_RK_089_fx_unknown_e4b997"),
  },
  {
    pattern: "rk_exact_RK_091_no_e688a6",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_1),
    build: (body, segment, trigger) =>
      grantRkFx("RK-091", "no_e688a6", body, segment, trigger, "rk_exact_RK_091_no_e688a6"),
  },
  {
    pattern: "rk_exact_RK_101_taigabonba",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_2),
    build: (body, segment, trigger) =>
      grantRkFx("RK-101", "taigabonba", body, segment, trigger, "rk_exact_RK_101_taigabonba"),
  },
  {
    pattern: "rk_exact_RK_107_ko",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_3),
    build: (body, segment, trigger) =>
      grantRkFx("RK-107", "ko", body, segment, trigger, "rk_exact_RK_107_ko"),
  },
  {
    pattern: "rk_exact_RK_110_no_e680a7",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_4),
    build: (body, segment, trigger) =>
      grantRkFx("RK-110", "no_e680a7", body, segment, trigger, "rk_exact_RK_110_no_e680a7"),
  },
  {
    pattern: "rk_exact_RK_111_fx_unknown_e99d9e",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_5),
    build: (body, segment, trigger) =>
      grantRkFx("RK-111", "fx_unknown_e99d9e", body, segment, trigger, "rk_exact_RK_111_fx_unknown_e99d9e"),
  },
  {
    pattern: "rk_exact_RK_115_endoobuwarudo",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_6),
    build: (body, segment, trigger) =>
      grantRkFx("RK-115", "endoobuwarudo", body, segment, trigger, "rk_exact_RK_115_endoobuwarudo"),
  },
  {
    pattern: "rk_exact_RK_120_nirashatoru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_7),
    build: (body, segment, trigger) =>
      grantRkFx("RK-120", "nirashatoru", body, segment, trigger, "rk_exact_RK_120_nirashatoru"),
  },
  {
    pattern: "rk_exact_RK_123_suru_hikari_no_tsubasa",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_8),
    build: (body, segment, trigger) =>
      grantRkFx("RK-123", "suru_hikari_no_tsubasa", body, segment, trigger, "rk_exact_RK_123_suru_hikari_no_tsubasa"),
  },
  {
    pattern: "rk_exact_RK_124_wo_mamoru_ru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_9),
    build: (body, segment, trigger) =>
      grantRkFx("RK-124", "wo_mamoru_ru", body, segment, trigger, "rk_exact_RK_124_wo_mamoru_ru"),
  },
  {
    pattern: "rk_exact_RK_126_gyarenrauza",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_10),
    build: (body, segment, trigger) =>
      grantRkFx("RK-126", "gyarenrauza", body, segment, trigger, "rk_exact_RK_126_gyarenrauza"),
  },
  {
    pattern: "rk_exact_RK_128_rengerurauza",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_11),
    build: (body, segment, trigger) =>
      grantRkFx("RK-128", "rengerurauza", body, segment, trigger, "rk_exact_RK_128_rengerurauza"),
  },
  {
    pattern: "rk_exact_RK_129_sandasupeida",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_12),
    build: (body, segment, trigger) =>
      grantRkFx("RK-129", "sandasupeida", body, segment, trigger, "rk_exact_RK_129_sandasupeida"),
  },
  {
    pattern: "rk_exact_RK_131_fx_unknown_e99fb3",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_13),
    build: (body, segment, trigger) =>
      grantRkFx("RK-131", "fx_unknown_e99fb3", body, segment, trigger, "rk_exact_RK_131_fx_unknown_e99fb3"),
  },
  {
    pattern: "rk_exact_RK_132_nobakuapu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_14),
    build: (body, segment, trigger) =>
      grantRkFx("RK-132", "nobakuapu", body, segment, trigger, "rk_exact_RK_132_nobakuapu"),
  },
  {
    pattern: "rk_exact_RK_135_fx_unknown_e6bd9c",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_15),
    build: (body, segment, trigger) =>
      grantRkFx("RK-135", "fx_unknown_e6bd9c", body, segment, trigger, "rk_exact_RK_135_fx_unknown_e6bd9c"),
  },
  {
    pattern: "rk_exact_RK_136_raidashuteingu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_16),
    build: (body, segment, trigger) =>
      grantRkFx("RK-136", "raidashuteingu", body, segment, trigger, "rk_exact_RK_136_raidashuteingu"),
  },
  {
    pattern: "rk_exact_RK_138_na",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_17),
    build: (body, segment, trigger) =>
      grantRkFx("RK-138", "na", body, segment, trigger, "rk_exact_RK_138_na"),
  },
  {
    pattern: "rk_exact_RK_139_hakanarii",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_18),
    build: (body, segment, trigger) =>
      grantRkFx("RK-139", "hakanarii", body, segment, trigger, "rk_exact_RK_139_hakanarii"),
  },
  {
    pattern: "rk_exact_RK_141_denebikubasuta",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_19),
    build: (body, segment, trigger) =>
      grantRkFx("RK-141", "denebikubasuta", body, segment, trigger, "rk_exact_RK_141_denebikubasuta"),
  },
  {
    pattern: "rk_exact_RK_146_denebukyandei",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_20),
    build: (body, segment, trigger) =>
      grantRkFx("RK-146", "denebukyandei", body, segment, trigger, "rk_exact_RK_146_denebukyandei"),
  },
  {
    pattern: "rk_exact_RK_146_denebukyandei_koreworashus",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_21),
    build: (body, segment, trigger) =>
      grantRkFx("RK-146", "denebukyandei_koreworashus", body, segment, trigger, "rk_exact_RK_146_denebukyandei_koreworashus"),
  },
  {
    pattern: "rk_exact_RK_147_redomu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_22),
    build: (body, segment, trigger) =>
      grantRkFx("RK-147", "redomu", body, segment, trigger, "rk_exact_RK_147_redomu"),
  },
  {
    pattern: "rk_exact_RK_148_furontoakusu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_23),
    build: (body, segment, trigger) =>
      grantRkFx("RK-148", "furontoakusu", body, segment, trigger, "rk_exact_RK_148_furontoakusu"),
  },
  {
    pattern: "rk_exact_RK_149_ryu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_24),
    build: (body, segment, trigger) =>
      grantRkFx("RK-149", "ryu", body, segment, trigger, "rk_exact_RK_149_ryu"),
  },
  {
    pattern: "rk_exact_RK_150_fx_unknown_e68e98",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_25),
    build: (body, segment, trigger) =>
      grantRkFx("RK-150", "fx_unknown_e68e98", body, segment, trigger, "rk_exact_RK_150_fx_unknown_e68e98"),
  },
  {
    pattern: "rk_exact_RK_153_ryo_e8bb8a",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_26),
    build: (body, segment, trigger) =>
      grantRkFx("RK-153", "ryo_e8bb8a", body, segment, trigger, "rk_exact_RK_153_ryo_e8bb8a"),
  },
  {
    pattern: "rk_exact_RK_154_gai",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_27),
    build: (body, segment, trigger) =>
      grantRkFx("RK-154", "gai", body, segment, trigger, "rk_exact_RK_154_gai"),
  },
  {
    pattern: "rk_exact_RK_155_ryo_noto",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_28),
    build: (body, segment, trigger) =>
      grantRkFx("RK-155", "ryo_noto", body, segment, trigger, "rk_exact_RK_155_ryo_noto"),
  },
  {
    pattern: "rk_exact_RK_157_nomumono",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_29),
    build: (body, segment, trigger) =>
      grantRkFx("RK-157", "nomumono", body, segment, trigger, "rk_exact_RK_157_nomumono"),
  },
  {
    pattern: "rk_exact_RK_159_v3kiku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_30),
    build: (body, segment, trigger) =>
      grantRkFx("RK-159", "v3kiku", body, segment, trigger, "rk_exact_RK_159_v3kiku"),
  },
  {
    pattern: "rk_exact_RK_160_nanoroboto",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_31),
    build: (body, segment, trigger) =>
      grantRkFx("RK-160", "nanoroboto", body, segment, trigger, "rk_exact_RK_160_nanoroboto"),
  },
  {
    pattern: "rk_exact_RK_163_no_chikara_e784a1",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_32),
    build: (body, segment, trigger) =>
      grantRkFx("RK-163", "no_chikara_e784a1", body, segment, trigger, "rk_exact_RK_163_no_chikara_e784a1"),
  },
  {
    pattern: "rk_exact_RK_165_shi_e681a9",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_33),
    build: (body, segment, trigger) =>
      grantRkFx("RK-165", "shi_e681a9", body, segment, trigger, "rk_exact_RK_165_shi_e681a9"),
  },
  {
    pattern: "rk_exact_RK_167_kaizabureigan",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_34),
    build: (body, segment, trigger) =>
      grantRkFx("RK-167", "kaizabureigan", body, segment, trigger, "rk_exact_RK_167_kaizabureigan"),
  },
  {
    pattern: "rk_exact_RK_168_tenkomoridaze",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_35),
    build: (body, segment, trigger) =>
      grantRkFx("RK-168", "tenkomoridaze", body, segment, trigger, "rk_exact_RK_168_tenkomoridaze"),
  },
  {
    pattern: "rk_exact_RK_171_kontorakuto",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_36),
    build: (body, segment, trigger) =>
      grantRkFx("RK-171", "kontorakuto", body, segment, trigger, "rk_exact_RK_171_kontorakuto"),
  },
  {
    pattern: "rk_exact_RK_173_no_e9acbc",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_37),
    build: (body, segment, trigger) =>
      grantRkFx("RK-173", "no_e9acbc", body, segment, trigger, "rk_exact_RK_173_no_e9acbc"),
  },
  {
    pattern: "rk_exact_RK_177_nami",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_38),
    build: (body, segment, trigger) =>
      grantRkFx("RK-177", "nami", body, segment, trigger, "rk_exact_RK_177_nami"),
  },
  {
    pattern: "rk_exact_RK_179_tari_geki",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_39),
    build: (body, segment, trigger) =>
      grantRkFx("RK-179", "tari_geki", body, segment, trigger, "rk_exact_RK_179_tari_geki"),
  },
  {
    pattern: "rk_exact_RK_180_shin",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_40),
    build: (body, segment, trigger) =>
      grantRkFx("RK-180", "shin", body, segment, trigger, "rk_exact_RK_180_shin"),
  },
  {
    pattern: "rk_exact_RK_181_haibaibuneiru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_41),
    build: (body, segment, trigger) =>
      grantRkFx("RK-181", "haibaibuneiru", body, segment, trigger, "rk_exact_RK_181_haibaibuneiru"),
  },
  {
    pattern: "rk_exact_RK_182_zburingaataku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_42),
    build: (body, segment, trigger) =>
      grantRkFx("RK-182", "zburingaataku", body, segment, trigger, "rk_exact_RK_182_zburingaataku"),
  },
  {
    pattern: "rk_exact_RK_183_zokiku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_43),
    build: (body, segment, trigger) =>
      grantRkFx("RK-183", "zokiku", body, segment, trigger, "rk_exact_RK_183_zokiku"),
  },
  {
    pattern: "rk_exact_RK_184_puru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_44),
    build: (body, segment, trigger) =>
      grantRkFx("RK-184", "puru", body, segment, trigger, "rk_exact_RK_184_puru"),
  },
  {
    pattern: "rk_exact_RK_185_fx_unknown_e59088",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_45),
    build: (body, segment, trigger) =>
      grantRkFx("RK-185", "fx_unknown_e59088", body, segment, trigger, "rk_exact_RK_185_fx_unknown_e59088"),
  },
  {
    pattern: "rk_exact_RK_186_jpanchi",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_46),
    build: (body, segment, trigger) =>
      grantRkFx("RK-186", "jpanchi", body, segment, trigger, "rk_exact_RK_186_jpanchi"),
  },
  {
    pattern: "rk_exact_RK_187_janboraidakiku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_47),
    build: (body, segment, trigger) =>
      grantRkFx("RK-187", "janboraidakiku", body, segment, trigger, "rk_exact_RK_187_janboraidakiku"),
  },
  {
    pattern: "rk_exact_RK_188_noejiento",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_48),
    build: (body, segment, trigger) =>
      grantRkFx("RK-188", "noejiento", body, segment, trigger, "rk_exact_RK_188_noejiento"),
  },
  {
    pattern: "rk_exact_RK_189_nopawa",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_49),
    build: (body, segment, trigger) =>
      grantRkFx("RK-189", "nopawa", body, segment, trigger, "rk_exact_RK_189_nopawa"),
  },
  {
    pattern: "rk_exact_RK_190_woeru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_50),
    build: (body, segment, trigger) =>
      grantRkFx("RK-190", "woeru", body, segment, trigger, "rk_exact_RK_190_woeru"),
  },
  {
    pattern: "rk_exact_RK_191_garaisodo",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_51),
    build: (body, segment, trigger) =>
      grantRkFx("RK-191", "garaisodo", body, segment, trigger, "rk_exact_RK_191_garaisodo"),
  },
  {
    pattern: "rk_exact_RK_192_agitofuangu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_52),
    build: (body, segment, trigger) =>
      grantRkFx("RK-192", "agitofuangu", body, segment, trigger, "rk_exact_RK_192_agitofuangu"),
  },
  {
    pattern: "rk_exact_RK_193_bamunidoru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_53),
    build: (body, segment, trigger) =>
      grantRkFx("RK-193", "bamunidoru", body, segment, trigger, "rk_exact_RK_193_bamunidoru"),
  },
  {
    pattern: "rk_exact_RK_194_gx05",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_54),
    build: (body, segment, trigger) =>
      grantRkFx("RK-194", "gx05", body, segment, trigger, "rk_exact_RK_194_gx05"),
  },
  {
    pattern: "rk_exact_RK_195_to_e5868d",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_55),
    build: (body, segment, trigger) =>
      grantRkFx("RK-195", "to_e5868d", body, segment, trigger, "rk_exact_RK_195_to_e5868d"),
  },
  {
    pattern: "rk_exact_RK_196_no_e9bb84",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_56),
    build: (body, segment, trigger) =>
      grantRkFx("RK-196", "no_e9bb84", body, segment, trigger, "rk_exact_RK_196_no_e9bb84"),
  },
  {
    pattern: "rk_exact_RK_197_ou_no",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_57),
    build: (body, segment, trigger) =>
      grantRkFx("RK-197", "ou_no", body, segment, trigger, "rk_exact_RK_197_ou_no"),
  },
  {
    pattern: "rk_exact_RK_198_doraibudeibaida",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_58),
    build: (body, segment, trigger) =>
      grantRkFx("RK-198", "doraibudeibaida", body, segment, trigger, "rk_exact_RK_198_doraibudeibaida"),
  },
  {
    pattern: "rk_exact_RK_199_zeruno",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_59),
    build: (body, segment, trigger) =>
      grantRkFx("RK-199", "zeruno", body, segment, trigger, "rk_exact_RK_199_zeruno"),
  },
  {
    pattern: "rk_exact_RK_200_reno_geki",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_60),
    build: (body, segment, trigger) =>
      grantRkFx("RK-200", "reno_geki", body, segment, trigger, "rk_exact_RK_200_reno_geki"),
  },
  {
    pattern: "rk_exact_RK_201_doraguburesu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_61),
    build: (body, segment, trigger) =>
      grantRkFx("RK-201", "doraguburesu", body, segment, trigger, "rk_exact_RK_201_doraguburesu"),
  },
  {
    pattern: "rk_exact_RK_203_akuserumodo",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_62),
    build: (body, segment, trigger) =>
      grantRkFx("RK-203", "akuserumodo", body, segment, trigger, "rk_exact_RK_203_akuserumodo"),
  },
  {
    pattern: "rk_exact_RK_205_furainguataka",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_63),
    build: (body, segment, trigger) =>
      grantRkFx("RK-205", "furainguataka", body, segment, trigger, "rk_exact_RK_205_furainguataka"),
  },
  {
    pattern: "rk_exact_RK_206_manaii",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_64),
    build: (body, segment, trigger) =>
      grantRkFx("RK-206", "manaii", body, segment, trigger, "rk_exact_RK_206_manaii"),
  },
  {
    pattern: "rk_exact_RK_208_geki_no",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_65),
    build: (body, segment, trigger) =>
      grantRkFx("RK-208", "geki_no", body, segment, trigger, "rk_exact_RK_208_geki_no"),
  },
  {
    pattern: "rk_exact_RK_209_karatareta",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_66),
    build: (body, segment, trigger) =>
      grantRkFx("RK-209", "karatareta", body, segment, trigger, "rk_exact_RK_209_karatareta"),
  },
  {
    pattern: "rk_exact_RK_210_baningushoto",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_67),
    build: (body, segment, trigger) =>
      grantRkFx("RK-210", "baningushoto", body, segment, trigger, "rk_exact_RK_210_baningushoto"),
  },
  {
    pattern: "rk_exact_RK_211_raitoningusurashu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_68),
    build: (body, segment, trigger) =>
      grantRkFx("RK-211", "raitoningusurashu", body, segment, trigger, "rk_exact_RK_211_raitoningusurashu"),
  },
  {
    pattern: "rk_exact_RK_212_reibareto",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_69),
    build: (body, segment, trigger) =>
      grantRkFx("RK-212", "reibareto", body, segment, trigger, "rk_exact_RK_212_reibareto"),
  },
  {
    pattern: "rk_exact_RK_214_inpakutosutabu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_70),
    build: (body, segment, trigger) =>
      grantRkFx("RK-214", "inpakutosutabu", body, segment, trigger, "rk_exact_RK_214_inpakutosutabu"),
  },
  {
    pattern: "rk_exact_RK_217_geki_e6bb91",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_71),
    build: (body, segment, trigger) =>
      grantRkFx("RK-217", "geki_e6bb91", body, segment, trigger, "rk_exact_RK_217_geki_e6bb91"),
  },
  {
    pattern: "rk_exact_RK_218_andedoworu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_72),
    build: (body, segment, trigger) =>
      grantRkFx("RK-218", "andedoworu", body, segment, trigger, "rk_exact_RK_218_andedoworu"),
  },
  {
    pattern: "rk_exact_RK_220_andedowoeru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_73),
    build: (body, segment, trigger) =>
      grantRkFx("RK-220", "andedowoeru", body, segment, trigger, "rk_exact_RK_220_andedowoeru"),
  },
  {
    pattern: "rk_exact_RK_221_ongekida_hi_honoo",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_74),
    build: (body, segment, trigger) =>
      grantRkFx("RK-221", "ongekida_hi_honoo", body, segment, trigger, "rk_exact_RK_221_ongekida_hi_honoo"),
  },
  {
    pattern: "rk_exact_RK_222_sound_strike_scorching_form",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_75),
    build: (body, segment, trigger) =>
      grantRkFx("RK-222", "sound_strike_scorching_form", body, segment, trigger, "rk_exact_RK_222_sound_strike_scorching_form"),
  },
  {
    pattern: "rk_exact_RK_223_geki_kaze_e99fb3",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_76),
    build: (body, segment, trigger) =>
      grantRkFx("RK-223", "geki_kaze_e99fb3", body, segment, trigger, "rk_exact_RK_223_geki_kaze_e99fb3"),
  },
  {
    pattern: "rk_exact_RK_224_sapoto",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_77),
    build: (body, segment, trigger) =>
      grantRkFx("RK-224", "sapoto", body, segment, trigger, "rk_exact_RK_224_sapoto"),
  },
  {
    pattern: "rk_exact_RK_227_geki_geki",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_78),
    build: (body, segment, trigger) =>
      grantRkFx("RK-227", "geki_geki", body, segment, trigger, "rk_exact_RK_227_geki_geki"),
  },
  {
    pattern: "rk_exact_RK_228_geki_kaze",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_79),
    build: (body, segment, trigger) =>
      grantRkFx("RK-228", "geki_kaze", body, segment, trigger, "rk_exact_RK_228_geki_kaze"),
  },
  {
    pattern: "rk_exact_RK_229_geki_baku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_80),
    build: (body, segment, trigger) =>
      grantRkFx("RK-229", "geki_baku", body, segment, trigger, "rk_exact_RK_229_geki_baku"),
  },
  {
    pattern: "rk_exact_RK_230_geki_3",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_81),
    build: (body, segment, trigger) =>
      grantRkFx("RK-230", "geki_3", body, segment, trigger, "rk_exact_RK_230_geki_3"),
  },
  {
    pattern: "rk_exact_RK_231_mizu_e6bd9c",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_82),
    build: (body, segment, trigger) =>
      grantRkFx("RK-231", "mizu_e6bd9c", body, segment, trigger, "rk_exact_RK_231_mizu_e6bd9c"),
  },
  {
    pattern: "rk_exact_RK_231_mizu_gatanwoeruto",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_83),
    build: (body, segment, trigger) =>
      grantRkFx("RK-231", "mizu_gatanwoeruto", body, segment, trigger, "rk_exact_RK_231_mizu_gatanwoeruto"),
  },
  {
    pattern: "rk_exact_RK_233_haiparaidakiku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_84),
    build: (body, segment, trigger) =>
      grantRkFx("RK-233", "haiparaidakiku", body, segment, trigger, "rk_exact_RK_233_haiparaidakiku"),
  },
  {
    pattern: "rk_exact_RK_234_shorudatakuru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_85),
    build: (body, segment, trigger) =>
      grantRkFx("RK-234", "shorudatakuru", body, segment, trigger, "rk_exact_RK_234_shorudatakuru"),
  },
  {
    pattern: "rk_exact_RK_235_abaranchikurashu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_86),
    build: (body, segment, trigger) =>
      grantRkFx("RK-235", "abaranchikurashu", body, segment, trigger, "rk_exact_RK_235_abaranchikurashu"),
  },
  {
    pattern: "rk_exact_RK_236_negatarosu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_87),
    build: (body, segment, trigger) =>
      grantRkFx("RK-236", "negatarosu", body, segment, trigger, "rk_exact_RK_236_negatarosu"),
  },
  {
    pattern: "rk_exact_RK_237_bashaakuatorunedo",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_88),
    build: (body, segment, trigger) =>
      grantRkFx("RK-237", "bashaakuatorunedo", body, segment, trigger, "rk_exact_RK_237_bashaakuatorunedo"),
  },
  {
    pattern: "rk_exact_RK_238_no_e9ad82",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_89),
    build: (body, segment, trigger) =>
      grantRkFx("RK-238", "no_e9ad82", body, segment, trigger, "rk_exact_RK_238_no_e9ad82"),
  },
  {
    pattern: "rk_exact_RK_240_no_4",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_90),
    build: (body, segment, trigger) =>
      grantRkFx("RK-240", "no_4", body, segment, trigger, "rk_exact_RK_240_no_4"),
  },
  {
    pattern: "rk_exact_RK_241_muriyarina",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_91),
    build: (body, segment, trigger) =>
      grantRkFx("RK-241", "muriyarina", body, segment, trigger, "rk_exact_RK_241_muriyarina"),
  },
  {
    pattern: "rk_exact_RK_246_garuruhauringusurashu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_92),
    build: (body, segment, trigger) =>
      grantRkFx("RK-246", "garuruhauringusurashu", body, segment, trigger, "rk_exact_RK_246_garuruhauringusurashu"),
  },
  {
    pattern: "rk_exact_RK_247_na_e4b88d",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_93),
    build: (body, segment, trigger) =>
      grantRkFx("RK-247", "na_e4b88d", body, segment, trigger, "rk_exact_RK_247_na_e4b88d"),
  },
  {
    pattern: "rk_exact_RK_255_urutorasaikuron",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_94),
    build: (body, segment, trigger) =>
      grantRkFx("RK-255", "urutorasaikuron", body, segment, trigger, "rk_exact_RK_255_urutorasaikuron"),
  },
  {
    pattern: "rk_exact_RK_256_kabutorosanda",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_95),
    build: (body, segment, trigger) =>
      grantRkFx("RK-256", "kabutorosanda", body, segment, trigger, "rk_exact_RK_256_kabutorosanda"),
  },
  {
    pattern: "rk_exact_RK_257_reda",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_96),
    build: (body, segment, trigger) =>
      grantRkFx("RK-257", "reda", body, segment, trigger, "rk_exact_RK_257_reda"),
  },
  {
    pattern: "rk_exact_RK_258_fx_unknown_e78c9b",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_97),
    build: (body, segment, trigger) =>
      grantRkFx("RK-258", "fx_unknown_e78c9b", body, segment, trigger, "rk_exact_RK_258_fx_unknown_e78c9b"),
  },
  {
    pattern: "rk_exact_RK_260_maguma",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_98),
    build: (body, segment, trigger) =>
      grantRkFx("RK-260", "maguma", body, segment, trigger, "rk_exact_RK_260_maguma"),
  },
  {
    pattern: "rk_exact_RK_261_riborukein",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_99),
    build: (body, segment, trigger) =>
      grantRkFx("RK-261", "riborukein", body, segment, trigger, "rk_exact_RK_261_riborukein"),
  },
  {
    pattern: "rk_exact_RK_263_fx_unknown_e6b6b2",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_100),
    build: (body, segment, trigger) =>
      grantRkFx("RK-263", "fx_unknown_e6b6b2", body, segment, trigger, "rk_exact_RK_263_fx_unknown_e6b6b2"),
  },
  {
    pattern: "rk_exact_RK_264_akurobatoban",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_101),
    build: (body, segment, trigger) =>
      grantRkFx("RK-264", "akurobatoban", body, segment, trigger, "rk_exact_RK_264_akurobatoban"),
  },
  {
    pattern: "rk_exact_RK_265_raideinguaro",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_102),
    build: (body, segment, trigger) =>
      grantRkFx("RK-265", "raideinguaro", body, segment, trigger, "rk_exact_RK_265_raideinguaro"),
  },
  {
    pattern: "rk_exact_RK_266_shotogan",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_103),
    build: (body, segment, trigger) =>
      grantRkFx("RK-266", "shotogan", body, segment, trigger, "rk_exact_RK_266_shotogan"),
  },
  {
    pattern: "rk_exact_RK_267_ma_ken",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_104),
    build: (body, segment, trigger) =>
      grantRkFx("RK-267", "ma_ken", body, segment, trigger, "rk_exact_RK_267_ma_ken"),
  },
  {
    pattern: "rk_exact_RK_268_chikara_e58886",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_105),
    build: (body, segment, trigger) =>
      grantRkFx("RK-268", "chikara_e58886", body, segment, trigger, "rk_exact_RK_268_chikara_e58886"),
  },
  {
    pattern: "rk_exact_RK_271_raijingumaiteikiku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_106),
    build: (body, segment, trigger) =>
      grantRkFx("RK-271", "raijingumaiteikiku", body, segment, trigger, "rk_exact_RK_271_raijingumaiteikiku"),
  },
  {
    pattern: "rk_exact_RK_272_raijingusupurashudoragon",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_107),
    build: (body, segment, trigger) =>
      grantRkFx("RK-272", "raijingusupurashudoragon", body, segment, trigger, "rk_exact_RK_272_raijingusupurashudoragon"),
  },
  {
    pattern: "rk_exact_RK_273_raijinguburasutopegasasu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_108),
    build: (body, segment, trigger) =>
      grantRkFx("RK-273", "raijinguburasutopegasasu", body, segment, trigger, "rk_exact_RK_273_raijinguburasutopegasasu"),
  },
  {
    pattern: "rk_exact_RK_274_nyumashinno",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_109),
    build: (body, segment, trigger) =>
      grantRkFx("RK-274", "nyumashinno", body, segment, trigger, "rk_exact_RK_274_nyumashinno"),
  },
  {
    pattern: "rk_exact_RK_275_zabaginbashigura",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_110),
    build: (body, segment, trigger) =>
      grantRkFx("RK-275", "zabaginbashigura", body, segment, trigger, "rk_exact_RK_275_zabaginbashigura"),
  },
  {
    pattern: "rk_exact_RK_276_kyokuginjanmama",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_111),
    build: (body, segment, trigger) =>
      grantRkFx("RK-276", "kyokuginjanmama", body, segment, trigger, "rk_exact_RK_276_kyokuginjanmama"),
  },
  {
    pattern: "rk_exact_RK_277_no_yami_womotarasu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_112),
    build: (body, segment, trigger) =>
      grantRkFx("RK-277", "no_yami_womotarasu", body, segment, trigger, "rk_exact_RK_277_no_yami_womotarasu"),
  },
  {
    pattern: "rk_exact_RK_279_dakubaizatsubai",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_113),
    build: (body, segment, trigger) =>
      grantRkFx("RK-279", "dakubaizatsubai", body, segment, trigger, "rk_exact_RK_279_dakubaizatsubai"),
  },
  {
    pattern: "rk_exact_RK_280_kaze_dan",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_114),
    build: (body, segment, trigger) =>
      grantRkFx("RK-280", "kaze_dan", body, segment, trigger, "rk_exact_RK_280_kaze_dan"),
  },
  {
    pattern: "rk_exact_RK_281_doragonfuaiyasutomu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_115),
    build: (body, segment, trigger) =>
      grantRkFx("RK-281", "doragonfuaiyasutomu", body, segment, trigger, "rk_exact_RK_281_doragonfuaiyasutomu"),
  },
  {
    pattern: "rk_exact_RK_283_no_e5a591",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_116),
    build: (body, segment, trigger) =>
      grantRkFx("RK-283", "no_e5a591", body, segment, trigger, "rk_exact_RK_283_no_e5a591"),
  },
  {
    pattern: "rk_exact_RK_284_desubanishu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_117),
    build: (body, segment, trigger) =>
      grantRkFx("RK-284", "desubanishu", body, segment, trigger, "rk_exact_RK_284_desubanishu"),
  },
  {
    pattern: "rk_exact_RK_286_inoriseto",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_118),
    build: (body, segment, trigger) =>
      grantRkFx("RK-286", "inoriseto", body, segment, trigger, "rk_exact_RK_286_inoriseto"),
  },
  {
    pattern: "rk_exact_RK_287_no_e79eac",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_119),
    build: (body, segment, trigger) =>
      grantRkFx("RK-287", "no_e79eac", body, segment, trigger, "rk_exact_RK_287_no_e79eac"),
  },
  {
    pattern: "rk_exact_RK_288_derutamuba",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_120),
    build: (body, segment, trigger) =>
      grantRkFx("RK-288", "derutamuba", body, segment, trigger, "rk_exact_RK_288_derutamuba"),
  },
  {
    pattern: "rk_exact_RK_289_jietoenjin",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_121),
    build: (body, segment, trigger) =>
      grantRkFx("RK-289", "jietoenjin", body, segment, trigger, "rk_exact_RK_289_jietoenjin"),
  },
  {
    pattern: "rk_exact_RK_290_no_e69cab",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_122),
    build: (body, segment, trigger) =>
      grantRkFx("RK-290", "no_e69cab", body, segment, trigger, "rk_exact_RK_290_no_e69cab"),
  },
  {
    pattern: "rk_exact_RK_291_ma_no_chikara",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_123),
    build: (body, segment, trigger) =>
      grantRkFx("RK-291", "ma_no_chikara", body, segment, trigger, "rk_exact_RK_291_ma_no_chikara"),
  },
  {
    pattern: "rk_exact_RK_292_tsuno",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_124),
    build: (body, segment, trigger) =>
      grantRkFx("RK-292", "tsuno", body, segment, trigger, "rk_exact_RK_292_tsuno"),
  },
  {
    pattern: "rk_exact_RK_293_suru_e68d95",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_125),
    build: (body, segment, trigger) =>
      grantRkFx("RK-293", "suru_e68d95", body, segment, trigger, "rk_exact_RK_293_suru_e68d95"),
  },
  {
    pattern: "rk_exact_RK_295_nitsu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_126),
    build: (body, segment, trigger) =>
      grantRkFx("RK-295", "nitsu", body, segment, trigger, "rk_exact_RK_295_nitsu"),
  },
  {
    pattern: "rk_exact_RK_296_raidakiku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_127),
    build: (body, segment, trigger) =>
      grantRkFx("RK-296", "raidakiku", body, segment, trigger, "rk_exact_RK_296_raidakiku"),
  },
  {
    pattern: "rk_exact_RK_298_mukishino",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_128),
    build: (body, segment, trigger) =>
      grantRkFx("RK-298", "mukishino", body, segment, trigger, "rk_exact_RK_298_mukishino"),
  },
  {
    pattern: "rk_exact_RK_299_dakuraidakiku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_129),
    build: (body, segment, trigger) =>
      grantRkFx("RK-299", "dakuraidakiku", body, segment, trigger, "rk_exact_RK_299_dakuraidakiku"),
  },
  {
    pattern: "rk_exact_RK_300_kurokuapu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_130),
    build: (body, segment, trigger) =>
      grantRkFx("RK-300", "kurokuapu", body, segment, trigger, "rk_exact_RK_300_kurokuapu"),
  },
  {
    pattern: "rk_exact_RK_301_ekusutendoraidatoshi",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_131),
    build: (body, segment, trigger) =>
      grantRkFx("RK-301", "ekusutendoraidatoshi", body, segment, trigger, "rk_exact_RK_301_ekusutendoraidatoshi"),
  },
  {
    pattern: "rk_exact_RK_302_wamunonitsu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_132),
    build: (body, segment, trigger) =>
      grantRkFx("RK-302", "wamunonitsu", body, segment, trigger, "rk_exact_RK_302_wamunonitsu"),
  },
  {
    pattern: "rk_exact_RK_303_no_e693ac",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_133),
    build: (body, segment, trigger) =>
      grantRkFx("RK-303", "no_e693ac", body, segment, trigger, "rk_exact_RK_303_no_e693ac"),
  },
  {
    pattern: "rk_exact_RK_304_soridoataku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_134),
    build: (body, segment, trigger) =>
      grantRkFx("RK-304", "soridoataku", body, segment, trigger, "rk_exact_RK_304_soridoataku"),
  },
  {
    pattern: "rk_exact_RK_305_no_2",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_135),
    build: (body, segment, trigger) =>
      grantRkFx("RK-305", "no_2", body, segment, trigger, "rk_exact_RK_305_no_2"),
  },
  {
    pattern: "rk_exact_RK_306_dainamikuchopu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_136),
    build: (body, segment, trigger) =>
      grantRkFx("RK-306", "dainamikuchopu", body, segment, trigger, "rk_exact_RK_306_dainamikuchopu"),
  },
  {
    pattern: "rk_exact_RK_307_wairudoshoto",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_137),
    build: (body, segment, trigger) =>
      grantRkFx("RK-307", "wairudoshoto", body, segment, trigger, "rk_exact_RK_307_wairudoshoto"),
  },
  {
    pattern: "rk_exact_RK_308_hakochiantahai",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_138),
    build: (body, segment, trigger) =>
      grantRkFx("RK-308", "hakochiantahai", body, segment, trigger, "rk_exact_RK_308_hakochiantahai"),
  },
  {
    pattern: "rk_exact_RK_309_niraretemiru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_139),
    build: (body, segment, trigger) =>
      grantRkFx("RK-309", "niraretemiru", body, segment, trigger, "rk_exact_RK_309_niraretemiru"),
  },
  {
    pattern: "rk_exact_RK_311_nosaniogaita",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_140),
    build: (body, segment, trigger) =>
      grantRkFx("RK-311", "nosaniogaita", body, segment, trigger, "rk_exact_RK_311_nosaniogaita"),
  },
  {
    pattern: "rk_exact_RK_316_fuesuru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_141),
    build: (body, segment, trigger) =>
      grantRkFx("RK-316", "fuesuru", body, segment, trigger, "rk_exact_RK_316_fuesuru"),
  },
  {
    pattern: "rk_exact_RK_317_podobateingu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_142),
    build: (body, segment, trigger) =>
      grantRkFx("RK-317", "podobateingu", body, segment, trigger, "rk_exact_RK_317_podobateingu"),
  },
  {
    pattern: "rk_exact_RK_318_buroukunfuangu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_143),
    build: (body, segment, trigger) =>
      grantRkFx("RK-318", "buroukunfuangu", body, segment, trigger, "rk_exact_RK_318_buroukunfuangu"),
  },
  {
    pattern: "rk_exact_RK_319_ikusajajimento",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_144),
    build: (body, segment, trigger) =>
      grantRkFx("RK-319", "ikusajajimento", body, segment, trigger, "rk_exact_RK_319_ikusajajimento"),
  },
  {
    pattern: "rk_exact_RK_321_sunekingudesubureiku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_145),
    build: (body, segment, trigger) =>
      grantRkFx("RK-321", "sunekingudesubureiku", body, segment, trigger, "rk_exact_RK_321_sunekingudesubureiku"),
  },
  {
    pattern: "rk_exact_RK_323_shadouberu",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_146),
    build: (body, segment, trigger) =>
      grantRkFx("RK-323", "shadouberu", body, segment, trigger, "rk_exact_RK_323_shadouberu"),
  },
  {
    pattern: "rk_exact_RK_324_inogaruze",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_147),
    build: (body, segment, trigger) =>
      grantRkFx("RK-324", "inogaruze", body, segment, trigger, "rk_exact_RK_324_inogaruze"),
  },
  {
    pattern: "rk_exact_RK_325_ikusapodo",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_148),
    build: (body, segment, trigger) =>
      grantRkFx("RK-325", "ikusapodo", body, segment, trigger, "rk_exact_RK_325_ikusapodo"),
  },
  {
    pattern: "rk_exact_RK_326_garurufuesuru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_149),
    build: (body, segment, trigger) =>
      grantRkFx("RK-326", "garurufuesuru", body, segment, trigger, "rk_exact_RK_326_garurufuesuru"),
  },
  {
    pattern: "rk_exact_RK_327_bashafuesuru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_150),
    build: (body, segment, trigger) =>
      grantRkFx("RK-327", "bashafuesuru", body, segment, trigger, "rk_exact_RK_327_bashafuesuru"),
  },
  {
    pattern: "rk_exact_RK_328_dogafuesuru",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_151),
    build: (body, segment, trigger) =>
      grantRkFx("RK-328", "dogafuesuru", body, segment, trigger, "rk_exact_RK_328_dogafuesuru"),
  },
  {
    pattern: "rk_exact_RK_329_no_e5b7a8",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_152),
    build: (body, segment, trigger) =>
      grantRkFx("RK-329", "no_e5b7a8", body, segment, trigger, "rk_exact_RK_329_no_e5b7a8"),
  },
  {
    pattern: "rk_exact_RK_331_ameijingumaiteikiku",
    test: (body) => normalizeBody(body) === normalizeBody(RK_TEXT_153),
    build: (body, segment, trigger) =>
      grantRkFx("RK-331", "ameijingumaiteikiku", body, segment, trigger, "rk_exact_RK_331_ameijingumaiteikiku"),
  },
];
