/** Auto-generated by scripts/generate-promoted-exact-patterns.ts — do not edit. */
import type { EffectDefinition } from "../dsl/types";
import type { ExtractedEffect, WikiEffectSegment } from "./types";
import { noteEffectIdFromBody, slugifyEffectId } from "./metaMaps";

type PatternMatch = {
  pattern: string;
  test: (body: string) => boolean;
  build: (
    body: string,
    segment: WikiEffectSegment,
    trigger: EffectDefinition["trigger"],
  ) => Omit<ExtractedEffect, "segmentIndex" | "needsFallback">;
};

function normalizeBody(body: string): string {
  return body.replace(/\s+/g, "").trim();
}

function triggerFromBody(
  body: string,
  fallback: EffectDefinition["trigger"],
): EffectDefinition["trigger"] {
  if (/バトルエリアに出たとき/.test(body)) return { type: "enter_battle" };
  if (/ラッシュしたとき|ラッシュするとき/.test(body)) return { type: "on_rush" };
  if (/アタックしたとき|アタックするとき/.test(body)) return { type: "on_attack" };
  if (/ストライクしたとき|ストライクして/.test(body)) return { type: "on_strike" };
  if (/撃破されて捨札になったとき/.test(body)) return { type: "on_destroy" };
  if (/敵軍ターン中/.test(body) || /にある間/.test(body)) return { type: "while_in_field" };
  return fallback;
}

function grantRmFx(
  cardId: string,
  effectId: string,
  body: string,
  segment: WikiEffectSegment,
  trigger: EffectDefinition["trigger"],
  matchedPattern: string,
  optional?: boolean,
): Omit<ExtractedEffect, "segmentIndex" | "needsFallback"> {
  return {
    id: segment.name ? slugifyEffectId(segment.name) : noteEffectIdFromBody(body),
    name: segment.name,
    text: body,
    trigger: triggerFromBody(body, trigger),
    optional: optional ?? /してもよい|してよい|選んでもよい/.test(body),
    effects: [
      {
        type: "grant_keyword",
        keyword: `rm_fx::${cardId}::${effectId}`,
        duration: /にある間/.test(body) ? "permanent" : "turn",
      },
    ],
    matchedPattern,
  };
}

const RM_TEXT_0 = `次の効果から１つ選び発動する⇒◎自軍山札から「宇宙刑事ギャバン」のカードを1枚選び、自軍ラッシュエリアに出してもよい。その後、山札をシャッフルする。◎自軍Sユニットを1体選ぶ。このターン、選んだユニットはSP1/4になる。`;
const RM_TEXT_1 = `次の効果から1つ選び発動する⇒◎自軍山札から「宇宙刑事シャリバン」のカードを1枚選び、自軍ラッシュエリアに出してもよい。その後、山札をシャッフルする。◎自軍Sユニットを1体選ぶ。このターン、選んだユニットの特徴に「レッド」を追加する。`;
const RM_TEXT_2 = `次の効果から1つ選び発動する⇒◎自軍山札から「宇宙刑事シャイダー」のカードを1枚選び、自軍ラッシュエリアに出してもよい。その後山札をシャッフルする。◎自軍Sユニットを1体選ぶ。このターン、選んだユニットの特徴に「ブルー」を追加する。`;
const RM_TEXT_3 = `敵軍山札の上から、自軍ダメージの点数と同じ数までオモテにする。そして、オモテにしたカードの中から、特徴「獣」または「恐竜」を持つユニットカードを好きな順で持ち主のラッシュエリアに出し、それ以外は山札に戻してシャッフルする。そうして出したユニットが1体以上あれば、自軍山札を見て、OTのLユニットのカードを1枚選び、自軍ラッシュエリアに出してもよい。その後、山札をシャッフルする。`;
const RM_TEXT_4 = `特徴「男」を持つ自軍ユニットを1体と、特徴「女」を持つ自軍ユニットを1体選び、選んだ2体の本来のBPを合計する。そして、合計したBP以下の敵軍ユニットを1体選び、持ち主のパワーゾーンに送る。`;
const RM_TEXT_5 = `敵軍バトルエリアから「これは敵軍ターン中、「SP1」以上のユニットとバトルしたときバトルに勝っても撃破される」と書かれた敵軍ユニットを1体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければ捨札にする。`;
const RM_TEXT_6 = `このオペレーションカードを使用するためにホールドしたコマンドの必要パワーの数字を見て、その数字と同じ必要パワーの数字を持つ敵軍Sユニットを1体選び撃破する。そうして撃破したユニットが捨札になる前に敵軍捨札を見て、撃破したユニットと同じカード名のユニットカードがあれば、このカードが捨札になるとき、かわりに手札に戻してもよい。`;
const RM_TEXT_7 = `自軍パワーゾーンのダメージになってるカードをすべてオモテにする。そして、相手は自分自身の山札を見て、ユニットカードを1枚選び、自分自身のラッシュエリアに出してもよい。その後、相手は自分自身の山札をシャッフルする。`;
const RM_TEXT_8 = `本来のBPが4000以上の敵軍Sユニットを1体選び、持ち主のパワーゾーンに送ってもよい。`;
const RM_TEXT_9 = `※これが自軍捨札にある間、自分が「電子星獣ドル」または「ギラン円盤」をラッシュするとき、ラッシュするユニットと同じカード名のユニットが自軍エリアになければ、その追加条件を満たさなくてもよい。`;
const RM_TEXT_10 = `これをラッシュしたとき、自軍パワーゾーンのオモテ向きのカードから、必要パワーの数字が4以下の、MユニットかSビークルのカードを1枚選んでもよい。そうしたとき、選んだカードを自軍ラッシュエリアに出す。`;
const RM_TEXT_11 = `自軍ターン中、これがバトルエリアに出たとき、OTを持つ自軍コマンドを2つホールドしてもよい。そうしたとき、これにライドしているユニットは、このターン、ライドオフしなくてもＲＣの効果を発動できる。`;
const RM_TEXT_12 = `これをラッシュしたとき、敵軍パワーゾーンのオモテ向きのカードから1枚選び、捨札にしてもよい。そうしたとき、敵軍捨札からカードを1枚選び敵軍パワーゾーンにオモテ向きで置く。`;
const RM_TEXT_13 = `これをラッシュしたとき、次の効果を発動できる⇒自軍山札を見て、特徴「車両」を持つSユニットのカードを1枚選び、相手に見せる。その後、山札をシャッフルし、選んだカードを山札の上に戻す。`;
const RM_TEXT_14 = `本来のBPが3000の敵軍ユニットを1体選び、持ち主のパワーゾーンに送ってもよい。`;
const RM_TEXT_15 = `自軍ターン中、これがバトルエリアに出たとき、自軍バトルエリアからビークルを1体選んでもよい。そうしたとき、選んだビークルにライドしているユニットがあれば、そのユニットをパワーゾーンに送る。その後、選んだビークルをパワーゾーンに送る。`;
const RM_TEXT_16 = `※これが自軍パワーゾーンでオモテ向きになっている間、特徴「宇宙刑事」を持つ自軍ユニットをラッシュしたとき、これを自軍ラッシュエリアに出してもよい。`;
const RM_TEXT_17 = `※SPが空欄ではない自軍Sユニットがあれば、これはバトルエリアに出られない。`;
const RM_TEXT_18 = `これが自軍ラッシュエリアにある間、OTを持つ自軍Lユニットは、アタックされるときBP+2000される。`;
const RM_TEXT_19 = `自軍ターン中、これがバトルエリアに出たとき、敵軍バトルエリアから、特徴「獣」または「恐竜」を持つBP8000以下のユニットを1体選び、持ち主のパワーゾーンに送ってもよい`;
const RM_TEXT_20 = `※これはバトルするとき、これとバトルするユニットの必要パワーの数字と同じ必要パワーの数字を持つ自軍コマンド1つにつきBP+2000される。`;
const RM_TEXT_21 = `自軍ターン中、これがバトルエリアに出たとき、自軍ラッシュエリアからユニットを1体選び、自軍コマンドゾーンにホールド状態で置いてもよい。置けなければこの効果は発動しない。`;
const RM_TEXT_22 = `自軍コマンドゾーンからカードを1枚選びホールドしてもよい。そうしたとき、ホールドしたカードの必要パワーの数字を見て、その数字と同じパワーの数字を持つカードを、敵軍パワーゾーンのオモテ向きのカードの中から1枚選び、ウラ返してダメージにする。`;
const RM_TEXT_23 = `これが自軍バトルエリアにある間、敵軍バトルフェイズ中、バトルエリアに出た特徴「メカ」を持つ敵軍Sユニットは、可能なら特徴「ヨロイ軍団」を持つユニットにアタックする。`;
const RM_TEXT_24 = `自軍ターン中、これがバトルエリアに出たとき、自軍ラッシュエリアから特徴「怪人」を持つユニットを1体選び、捨札にしてもよい。そうしたとき、相手の手札を見ないで1枚選ぶ。相手は選ばれたカードを自分自身の山札の上に戻すか、自分自身のパワーゾーンに置くか、自分自身のコマンドゾーンにホールド状態で置くかを選ぶ。`;
const RM_TEXT_25 = `これが自軍エリアにある間、自軍ラッシュフェイズ中、DAを持つ自軍コマンドを3つホールドしてもよい。そうしたとき、自軍捨札からDAを持ち特徴「メカ」を持つSユニットのカードを1枚選び、自軍ラッシュエリアに出す。`;
const RM_TEXT_26 = `自軍ターン中、これがバトルエリアに出たとき、敵軍捨札からユニットカードを1枚選んでもよい。そうしたとき、選んだユニットカードと同じカード名の敵軍ユニットを1体選び、持ち主のパワーゾーンにダメージにして置く。`;
const RM_TEXT_27 = `敵軍ユニットを1体選んでもよい。そうしたとき、選んだユニットと同じカード名の敵軍ユニットが、選んだユニット以外にあれば、選んだユニットを持ち主のパワーゾーンにダメージにして置く。`;
const RM_TEXT_28 = `これをラッシュしたとき、自軍エリアの「鳥忍 カラス天狗」が3体以下なら、3体になるまで、自軍パワーゾーンのオモテ向きのカードか自軍コマンドゾーンのカードから「鳥忍 カラス天狗」のカードを選び、自軍ラッシュエリアに出してもよい。`;
const RM_TEXT_29 = `敵軍バトルエリアにある、特徴「男」または「女」を持たないSユニットを、すべて持ち主のコマンドゾーンにホールド状態で置く。置けなければ捨札にする。`;
const RM_TEXT_30 = `※このユニットからコンビネーションする特徴「メカ」を持つSユニットは、ライドオフしなくてもＲＣの効果を発動できる。`;
const RM_TEXT_31 = `敵軍Sユニットの中から1体を、相手に選ばせてもよい（相手が選ぶたび、まだ相手に選ばれてない敵軍Sユニットがあれば、その中から選びなおさせてもよい。ただし、自軍コマンドを1つホールドすること）。その後、相手が最終的に選んだ1体を撃破する。`;
const RM_TEXT_32 = `自軍ターン中、これがバトルエリアに出たとき、敵軍バトルエリアから、ライドされていないSビークルを1体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければこの効果は発動できない。`;
const RM_TEXT_33 = `敵軍バトルエリアから、DAまたはOTを持つSユニットを1体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければこの効果は発動できない。（この効果は、特徴「スワット」を持つユニットからコンビネーションするとき、ナンバーに関係なく発動する）`;
const RM_TEXT_34 = `敵軍コマンドゾーンから、DAまたはOTを持つカードを1枚選び、持ち主のパワーゾーンに送る。（この効果は、特徴「スワット」を持つユニットからコンビネーションするとき、ナンバーに関係なく発動する）`;
const RM_TEXT_35 = `敵軍パワーゾーンのオモテ向きのカードにSユニットのカードが無ければ、次の効果を発動できる⇒DAまたはOTを持つ敵軍Mユニットを1体選び、持ち主のコマンドゾーンにホールド状態で置く。置けなければ捨札にする。（この効果は、特徴「スワット」を持つユニットからコンビネーションするとき、ナンバーに関係なく発動する）`;
const RM_TEXT_36 = `これは、自軍エリアに「ビートルーダー」があれば「SP1」になり、「スタッガータンク」があればBP+3000され、「レッドジャイロ」があればレジストを得る。`;
const RM_TEXT_37 = `自軍ターン中、これがバトルエリアに出たとき、自軍エリアに「ビートルーダー」があれば、次の効果を発動できる⇒特徴「メカ」を持つ敵軍Mユニットを1体選びホールドする。`;
const RM_TEXT_38 = `自軍ターン中、これがバトルエリアに出たとき、敵軍バトルエリアからBP3000以下の特徴「航空機」を持つ敵軍ユニットを1体選びホールドする。`;
const RM_TEXT_39 = `ライド中の敵軍Sユニットを1体選んでもよい。そうしたとき、相手はそのSユニットか、そのSユニットがライドしているビークルのうち、どちらか1体を選び捨札にする。`;
const RM_TEXT_40 = `レジストを持たない敵軍Sユニットを1体選びホールドしてもよい。`;
const RM_TEXT_41 = `これが自軍ラッシュエリアにある間、次の効果を発動する⇒特徴「メカ」を持つユニットと、特徴「メカ」を持つビークルに、特徴「昆虫」を追加する。`;
const RM_TEXT_42 = `これが自軍ラッシュエリアにある間、WBを持つ自軍Sユニットがバトルエリアに出たとき、常駐している自軍オペレーションに重ねたカードがあれば、その中から1枚選び、自分の手札に加えてもよい（ウラ向きのカードはウラ向きのまま選ぶ）。`;
const RM_TEXT_43 = `これをラッシュしたとき、次の効果を発動できる⇒敵軍バトルエリアから、スクラムを持つユニットを1体選び、ラッシュエリアに戻す。`;
const RM_TEXT_44 = `これが自軍エリアにある間、敵軍ターン中、自軍バトルエリアにある特徴「女」を持つユニットが、特徴「男」を持つユニットにアタックされたとき、自軍コマンドを1つホールドしてもよい。 そうしたとき、アタックされた自軍ユニットをラッシュエリアに戻す。このときバトルは行われない。`;

export const RM_EXACT_PATTERNS: PatternMatch[] = [
  {
    pattern: "rm_exact_RM_001_note_e6aca1e381aee58ab9e69e9c",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_0),
    build: (body, segment, trigger) =>
      grantRmFx("RM-001", "note_e6aca1e381aee58ab9e69e9c", body, segment, trigger, "rm_exact_RM_001_note_e6aca1e381aee58ab9e69e9c"),
  },
  {
    pattern: "rm_exact_RM_002_note_e6aca1e381aee58ab9e69e9c",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_1),
    build: (body, segment, trigger) =>
      grantRmFx("RM-002", "note_e6aca1e381aee58ab9e69e9c", body, segment, trigger, "rm_exact_RM_002_note_e6aca1e381aee58ab9e69e9c"),
  },
  {
    pattern: "rm_exact_RM_003_note_e6aca1e381aee58ab9e69e9c",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_2),
    build: (body, segment, trigger) =>
      grantRmFx("RM-003", "note_e6aca1e381aee58ab9e69e9c", body, segment, trigger, "rm_exact_RM_003_note_e6aca1e381aee58ab9e69e9c"),
  },
  {
    pattern: "rm_exact_RM_004_note_e695b5e8bb8de5b1b1e69cad",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_3),
    build: (body, segment, trigger) =>
      grantRmFx("RM-004", "note_e695b5e8bb8de5b1b1e69cad", body, segment, trigger, "rm_exact_RM_004_note_e695b5e8bb8de5b1b1e69cad"),
  },
  {
    pattern: "rm_exact_RM_005_note_e789b9e5beb4e3808ce794b7",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_4),
    build: (body, segment, trigger) =>
      grantRmFx("RM-005", "note_e789b9e5beb4e3808ce794b7", body, segment, trigger, "rm_exact_RM_005_note_e789b9e5beb4e3808ce794b7"),
  },
  {
    pattern: "rm_exact_RM_008_note_e695b5e8bb8de38390e38388",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_5),
    build: (body, segment, trigger) =>
      grantRmFx("RM-008", "note_e695b5e8bb8de38390e38388", body, segment, trigger, "rm_exact_RM_008_note_e695b5e8bb8de38390e38388"),
  },
  {
    pattern: "rm_exact_RM_015_note_e38193e381aee382aae3839a",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_6),
    build: (body, segment, trigger) =>
      grantRmFx("RM-015", "note_e38193e381aee382aae3839a", body, segment, trigger, "rm_exact_RM_015_note_e38193e381aee382aae3839a"),
  },
  {
    pattern: "rm_exact_RM_016_note_e887aae8bb8de38391e383af",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_7),
    build: (body, segment, trigger) =>
      grantRmFx("RM-016", "note_e887aae8bb8de38391e383af", body, segment, trigger, "rm_exact_RM_016_note_e887aae8bb8de38391e383af"),
  },
  {
    pattern: "rm_exact_RM_018_gyabandainamiku",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_8),
    build: (body, segment, trigger) =>
      grantRmFx("RM-018", "gyabandainamiku", body, segment, trigger, "rm_exact_RM_018_gyabandainamiku"),
  },
  {
    pattern: "rm_exact_RM_019_note_e280bbe38193e3828ce3818c",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_9),
    build: (body, segment, trigger) =>
      grantRmFx("RM-019", "note_e280bbe38193e3828ce3818c", body, segment, trigger, "rm_exact_RM_019_note_e280bbe38193e3828ce3818c"),
  },
  {
    pattern: "rm_exact_RM_021_bikuru",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_10),
    build: (body, segment, trigger) =>
      grantRmFx("RM-021", "bikuru", body, segment, trigger, "rm_exact_RM_021_bikuru"),
  },
  {
    pattern: "rm_exact_RM_022_saibarianrezasupido",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_11),
    build: (body, segment, trigger) =>
      grantRmFx("RM-022", "saibarianrezasupido", body, segment, trigger, "rm_exact_RM_022_saibarianrezasupido"),
  },
  {
    pattern: "rm_exact_RM_023_fx_unknown_e59cb0",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_12),
    build: (body, segment, trigger) =>
      grantRmFx("RM-023", "fx_unknown_e59cb0", body, segment, trigger, "rm_exact_RM_023_fx_unknown_e59cb0"),
  },
  {
    pattern: "rm_exact_RM_024_fx_unknown_e690ad",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_13),
    build: (body, segment, trigger) =>
      grantRmFx("RM-024", "fx_unknown_e690ad", body, segment, trigger, "rm_exact_RM_024_fx_unknown_e690ad"),
  },
  {
    pattern: "rm_exact_RM_025_sharibankurashu",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_14),
    build: (body, segment, trigger) =>
      grantRmFx("RM-025", "sharibankurashu", body, segment, trigger, "rm_exact_RM_025_sharibankurashu"),
  },
  {
    pattern: "rm_exact_RM_026_fx_unknown_e58f8e",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_15),
    build: (body, segment, trigger) =>
      grantRmFx("RM-026", "fx_unknown_e58f8e", body, segment, trigger, "rm_exact_RM_026_fx_unknown_e58f8e"),
  },
  {
    pattern: "rm_exact_RM_028_note_e280bbe38193e3828ce3818c",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_16),
    build: (body, segment, trigger) =>
      grantRmFx("RM-028", "note_e280bbe38193e3828ce3818c", body, segment, trigger, "rm_exact_RM_028_note_e280bbe38193e3828ce3818c"),
  },
  {
    pattern: "rm_exact_RM_029_note_e280bb5350e3818ce7a9bae6",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_17),
    build: (body, segment, trigger) =>
      grantRmFx("RM-029", "note_e280bb5350e3818ce7a9bae6", body, segment, trigger, "rm_exact_RM_029_note_e280bb5350e3818ce7a9bae6"),
  },
  {
    pattern: "rm_exact_RM_030_daireonreza",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_18),
    build: (body, segment, trigger) =>
      grantRmFx("RM-030", "daireonreza", body, segment, trigger, "rm_exact_RM_030_daireonreza"),
  },
  {
    pattern: "rm_exact_RM_031_kozumikukurashu",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_19),
    build: (body, segment, trigger) =>
      grantRmFx("RM-031", "kozumikukurashu", body, segment, trigger, "rm_exact_RM_031_kozumikukurashu"),
  },
  {
    pattern: "rm_exact_RM_033_note_e280bbe38193e3828ce381af",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_20),
    build: (body, segment, trigger) =>
      grantRmFx("RM-033", "note_e280bbe38193e3828ce381af", body, segment, trigger, "rm_exact_RM_033_note_e280bbe38193e3828ce381af"),
  },
  {
    pattern: "rm_exact_RM_033_no_6",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_21),
    build: (body, segment, trigger) =>
      grantRmFx("RM-033", "no_6", body, segment, trigger, "rm_exact_RM_033_no_6"),
  },
  {
    pattern: "rm_exact_RM_034_na_geki",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_22),
    build: (body, segment, trigger) =>
      grantRmFx("RM-034", "na_geki", body, segment, trigger, "rm_exact_RM_034_na_geki"),
  },
  {
    pattern: "rm_exact_RM_035_yoroino",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_23),
    build: (body, segment, trigger) =>
      grantRmFx("RM-035", "yoroino", body, segment, trigger, "rm_exact_RM_035_yoroino"),
  },
  {
    pattern: "rm_exact_RM_037_wobanu",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_24),
    build: (body, segment, trigger) =>
      grantRmFx("RM-037", "wobanu", body, segment, trigger, "rm_exact_RM_037_wobanu"),
  },
  {
    pattern: "rm_exact_RM_038_noto",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_25),
    build: (body, segment, trigger) =>
      grantRmFx("RM-038", "noto", body, segment, trigger, "rm_exact_RM_038_noto"),
  },
  {
    pattern: "rm_exact_RM_039_zan_ri_e58d81",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_26),
    build: (body, segment, trigger) =>
      grantRmFx("RM-039", "zan_ri_e58d81", body, segment, trigger, "rm_exact_RM_039_zan_ri_e58d81"),
  },
  {
    pattern: "rm_exact_RM_041_aiamunadonosankyu",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_27),
    build: (body, segment, trigger) =>
      grantRmFx("RM-041", "aiamunadonosankyu", body, segment, trigger, "rm_exact_RM_041_aiamunadonosankyu"),
  },
  {
    pattern: "rm_exact_RM_043_fx_31",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_28),
    build: (body, segment, trigger) =>
      grantRmFx("RM-043", "fx_31", body, segment, trigger, "rm_exact_RM_043_fx_31"),
  },
  {
    pattern: "rm_exact_RM_044_jandejiku",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_29),
    build: (body, segment, trigger) =>
      grantRmFx("RM-044", "jandejiku", body, segment, trigger, "rm_exact_RM_044_jandejiku"),
  },
  {
    pattern: "rm_exact_RM_045_note_e280bbe38193e381aee383a6",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_30),
    build: (body, segment, trigger) =>
      grantRmFx("RM-045", "note_e280bbe38193e381aee383a6", body, segment, trigger, "rm_exact_RM_045_note_e280bbe38193e381aee383a6"),
  },
  {
    pattern: "rm_exact_RM_045_hominguburido",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_31),
    build: (body, segment, trigger) =>
      grantRmFx("RM-045", "hominguburido", body, segment, trigger, "rm_exact_RM_045_hominguburido"),
  },
  {
    pattern: "rm_exact_RM_047_bigukyanon",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_32),
    build: (body, segment, trigger) =>
      grantRmFx("RM-047", "bigukyanon", body, segment, trigger, "rm_exact_RM_047_bigukyanon"),
  },
  {
    pattern: "rm_exact_RM_048_fureimusurowa",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_33),
    build: (body, segment, trigger) =>
      grantRmFx("RM-048", "fureimusurowa", body, segment, trigger, "rm_exact_RM_048_fureimusurowa"),
  },
  {
    pattern: "rm_exact_RM_049_deikuteita",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_34),
    build: (body, segment, trigger) =>
      grantRmFx("RM-049", "deikuteita", body, segment, trigger, "rm_exact_RM_049_deikuteita"),
  },
  {
    pattern: "rm_exact_RM_050_misairurancha",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_35),
    build: (body, segment, trigger) =>
      grantRmFx("RM-050", "misairurancha", body, segment, trigger, "rm_exact_RM_050_misairurancha"),
  },
  {
    pattern: "rm_exact_RM_051_megabitofuomeshon",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_36),
    build: (body, segment, trigger) =>
      grantRmFx("RM-051", "megabitofuomeshon", body, segment, trigger, "rm_exact_RM_051_megabitofuomeshon"),
  },
  {
    pattern: "rm_exact_RM_053_doriruatachimento",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_37),
    build: (body, segment, trigger) =>
      grantRmFx("RM-053", "doriruatachimento", body, segment, trigger, "rm_exact_RM_053_doriruatachimento"),
  },
  {
    pattern: "rm_exact_RM_054_redoparusa",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_38),
    build: (body, segment, trigger) =>
      grantRmFx("RM-054", "redoparusa", body, segment, trigger, "rm_exact_RM_054_redoparusa"),
  },
  {
    pattern: "rm_exact_RM_056_suteingakuro",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_39),
    build: (body, segment, trigger) =>
      grantRmFx("RM-056", "suteingakuro", body, segment, trigger, "rm_exact_RM_056_suteingakuro"),
  },
  {
    pattern: "rm_exact_RM_057_suteingapurazuma",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_40),
    build: (body, segment, trigger) =>
      grantRmFx("RM-057", "suteingapurazuma", body, segment, trigger, "rm_exact_RM_057_suteingapurazuma"),
  },
  {
    pattern: "rm_exact_RM_058_no_e69886",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_41),
    build: (body, segment, trigger) =>
      grantRmFx("RM-058", "no_e69886", body, segment, trigger, "rm_exact_RM_058_no_e69886"),
  },
  {
    pattern: "rm_exact_RM_059_torankuno",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_42),
    build: (body, segment, trigger) =>
      grantRmFx("RM-059", "torankuno", body, segment, trigger, "rm_exact_RM_059_torankuno"),
  },
  {
    pattern: "rm_exact_RM_061_misairu",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_43),
    build: (body, segment, trigger) =>
      grantRmFx("RM-061", "misairu", body, segment, trigger, "rm_exact_RM_061_misairu"),
  },
  {
    pattern: "rm_exact_RM_062_rinasuteki",
    test: (body) => normalizeBody(body) === normalizeBody(RM_TEXT_44),
    build: (body, segment, trigger) =>
      grantRmFx("RM-062", "rinasuteki", body, segment, trigger, "rm_exact_RM_062_rinasuteki"),
  },
];
