/** Japanese labels for named unit / NC / operation effect ids (UI + logs). */
export const EFFECT_LABELS: Record<string, string> = {
  // NC
  grant_sp1: "SP+1",
  eagle_diving: "イーグルダイビング",
  moss_breaker: "モスブレイカー",
  ruin_survey: "遺跡調査",
  pit_in_dive: "ピットインダイブ",
  red_fire: "レッドファイア",
  yellow_thunder: "イエローサンダー",
  future_sight: "未来予知",
  pink_storm: "ピンクストーム",
  green_ground: "グリーングラウンド",
  bouken_javelin: "冒険ジャベリン",
  radial_hammer: "ラジアルハンマー",
  blow_knuckle: "ブロウナックル",
  magical_dragon_shoot: "マジカルドラゴンシュート",
  // on rush
  armor_attack: "アーマーアタック",
  tyranno_sonic: "ティラノソニック",
  moss_blizzard: "モスブリザード",
  ptera_beam: "プテラビーム",
  // conditional (battle entry)
  judgment_sword: "ジャッジメントソード",
  justice_flasher: "ジャスティスフラッシャー",
  super_drill: "超ドリル進化",
  // enter battle / passive
  destroy_enemy_bp4000: "撃破",
  sky_magic_slash: "天空魔法斬り",
  super_shield: "超シールド進化",
  super_cutter: "超カッター進化",
  focused_breakthrough: "一点突破",
  // on attack / field auras
  shark_jaws: "シャークジョーズ",
  panther_claw: "パンサークロー",
  signal_cannon: "シグナルキャノン",
  tricera_cannon: "トリケラキャノン",
  guardian_god: "守護神",
  pat_signer: "パットサイン",
  // operations
  goren_storm: "ゴーレンストーム",
  jacker_hurricane: "ジャッカーハリケーン",
  battle_dance: "バトルダンス",
  denji_machine: "デンジマシン",
  land_balkan: "ランドバルカン",
  new_gymnastics: "新体操",
  place_in_power: "パワー加速",
  judgment: "ジャッジメント",
  dynamite_power: "ダイナマイトパワー",
  super_brain: "超頭脳",
  power_bazooka: "パワーバズーカ",
  prism_power: "プリズムパワー",
  aura_power: "オーラパワー",
  science_academy: "科学アカデミー",
  shiron_light: "シロンの光",
  five_tech: "ファイブテクター",
  bird_nick_wave: "バードニックウェーブ",
  dino_chronicle: "恐竜クロニクル",
  ki_power: "気パワー",
  hidden_ninja: "隠れ忍",
  super_power: "超パワー",
  cyber_s_rider: "サイバーSライダー",
  earth_force: "アースの力",
  discard_s_unit_to_hand: "S回収",
  compression_freeze: "圧縮フリーズ",
  bp_boost_4000: "BP+4000",
  shippu_ninja: "疾風忍",
  dino_guts: "恐竜根性",
  courage_magic: "勇気の魔法",
  adventure: "冒険",
  plasma_energy: "プラズマエネルギー",
  discard_to_hand: "捨札回収",
  lightning_gravity: "稲妻重力",
  // Legend 2 operations
  hidora_egg: "ヒドラー兵の卵",
  infinite_chain: "無限連鎖",
  // Legend 2 NC
  competition: "競争",
  ryuu_geki_ken: "龍撃剣",
  tricera_lance: "トリケランス",
  ptera_arrow: "プテラアロー",
  life_rescue: "人命救助",
  super_ninpo_lion_dance: "超忍法・舞獅子",
  super_ninpo_water_transform: "超忍法・水変化",
  dark_dual_blade: "暗黒二刀流・巌流剣",
  space_ninpo_rope_skull: "宇宙忍法・縄頭蓋",
  juu_kun_do: "ジュウクンドー",
  deace_sniper: "ディースナイパー",
  green_crush: "グリーンクラッシュ",
  backup_request: "応援要請",
  zenibomb: "ゼニボム",
  // Legend 2 on rush
  rescue_activity: "救助活動",
  sure_win_combination: "必勝合体",
  firefighting: "消火作業",
  dismantling: "解体作業",
  heavenly_disaster: "天の災",
  karakuri_great_tsunami: "カラクリ忍法・大津波",
  air_transport: "空輸搬送",
  // Legend 2 conditional
  val_shield: "バルシールド",
  dance_of_darkness: "闇の舞",
  ghost_absorption: "幽魔吸収",
  precious_guardian: "プレシャスの護り手",
  shift_up: "シフトアップ",
  karakuri_fire_hawk: "カラクリ忍法・火炎鷹",
  tantrum: "かんしゃく",
  cry: "鳴き声",
  // Legend 2 enter battle
  mane_hurricane: "タテガミハリケーン",
  phantom_illusion: "ファントムイリュージョン",
  ruin_excavation: "遺跡発掘",
  // Legend 2 on attack / field
  val_cannon: "バルカン砲",
  dump_punch: "ダンプパンチ",
  ptera_dagger: "プテラダガー",
  adventure_drive_sword: "轟轟剣アドベンチャードライブ",
  jaguar_mothership: "母艦",
  bio_buster: "バイバスター",
  medical_rescue: "救護活動",
  traffic_control: "交通整理",
  karakuri_lion_chain: "カラクリ忍法・連獅子",
  dekabase_mothership: "母艦",
  fire_spin_blade: "ファイヤースピンブレード",
  seabed_survey: "海底探査",
  opponent_may_draw_on_enter: "進入時ドロー",
};

export function getEffectLabel(effectId: string): string {
  return EFFECT_LABELS[effectId] ?? effectId;
}
