import type { RkUiTestSpec } from "./types";

/** RK-001〜RK-010 — wiki: docs/wiki/cards/RK-00x.md */
export const RK_BATCH_01: RkUiTestSpec[] = [
  {
    cardId: "RK-001",
    wikiRef: "docs/wiki/cards/RK-001.md",
    name: "改造人間",
    kind: "permanent",
    powerCost: 0,
    category: "ET",
    textSnippets: ["※常駐", "改造人間", "男", "女"],
    expectedMechanisms: ["operation_permanent_place", "passive_engine_only"],
    expectedDslKeywords: ["resident"],
  },
  {
    cardId: "RK-002",
    wikiRef: "docs/wiki/cards/RK-002.md",
    name: "V3ホッパー",
    kind: "instant",
    powerCost: 0,
    category: "ET",
    textSnippets: ["山札の上から3枚", "好きな順で戻す"],
    expectedMechanisms: ["operation_drag_direct", "effect_choice_modal"],
    expectedDropRoute: "direct_play",
    expectedDslKeywords: ["deck_scry_three_reorder"],
  },
  {
    cardId: "RK-003",
    wikiRef: "docs/wiki/cards/RK-003.md",
    name: "カイゾーグ",
    kind: "permanent",
    powerCost: 2,
    category: "ET",
    textSnippets: ["※常駐", "撃破されて捨札", "山札の下に戻す"],
    expectedMechanisms: ["operation_permanent_place", "passive_engine_only"],
    expectedDslKeywords: ["resident"],
  },
  {
    cardId: "RK-004",
    wikiRef: "docs/wiki/cards/RK-004.md",
    name: "ギギの腕輪",
    kind: "counter",
    powerCost: 3,
    category: "WB",
    textSnippets: ["※カウンター", "BP+2000"],
    expectedMechanisms: ["operation_counter_reaction"],
    expectedDslKeywords: ["counter_defender_bp_2000"],
  },
  {
    cardId: "RK-005",
    wikiRef: "docs/wiki/cards/RK-005.md",
    name: "超電子ダイナモ",
    kind: "instant",
    powerCost: 0,
    category: "ET",
    textSnippets: ["改造人間", "SPが空欄ではない", "1点ダメージ"],
    expectedMechanisms: ["operation_drag_direct"],
    expectedDropRoute: "direct_play",
    engineGaps: [
      "DSL primitive が deal_damage になっており、ユニット選択＋撃破時ダメージ能力の grant が未実装",
    ],
  },
  {
    cardId: "RK-006",
    wikiRef: "docs/wiki/cards/RK-006.md",
    name: "セイリングジャンプ",
    kind: "permanent",
    powerCost: 3,
    category: "ET",
    textSnippets: ["※常駐", "ライドしていない", "アタックされない"],
    expectedMechanisms: ["operation_permanent_place", "passive_engine_only"],
    expectedDslKeywords: ["resident"],
  },
  {
    cardId: "RK-007",
    wikiRef: "docs/wiki/cards/RK-007.md",
    name: "メンテナンス",
    kind: "instant",
    powerCost: 2,
    category: "ET",
    textSnippets: ["リリース状態のSユニット", "改造人間", "ホールド状態"],
    expectedMechanisms: ["operation_drag_direct", "effect_choice_modal"],
    expectedDropRoute: "direct_play",
    expectedDslKeywords: ["command_return_then_recruit_discard"],
  },
  {
    cardId: "RK-008",
    wikiRef: "docs/wiki/cards/RK-008.md",
    name: "メカニック忍者",
    kind: "counter",
    powerCost: 4,
    category: "ET",
    textSnippets: ["※カウンター", "改造人間", "バトルは行われない"],
    expectedMechanisms: ["operation_counter_reaction"],
    expectedDslKeywords: ["counter_hold_kamen_s"],
  },
  {
    cardId: "RK-009",
    wikiRef: "docs/wiki/cards/RK-009.md",
    name: "二人の世紀王",
    kind: "counter",
    powerCost: 5,
    category: "MA",
    textSnippets: ["※カウンター", "手札に戻す", "BP+1000"],
    expectedMechanisms: ["operation_counter_reaction"],
    expectedDslKeywords: ["counter_return_all_s_on_attack"],
  },
  {
    cardId: "RK-010",
    wikiRef: "docs/wiki/cards/RK-010.md",
    name: "ハイブリッドエネルギー",
    kind: "permanent",
    powerCost: 4,
    category: "MA",
    textSnippets: ["※常駐", "オモテにする", "BP+1000"],
    expectedMechanisms: ["operation_permanent_place", "passive_engine_only"],
    expectedDslKeywords: ["resident"],
  },
];
