import type { RkUiTestSpec } from "./types";

/** RK-011〜RK-020 — wiki: docs/wiki/cards/RK-01x.md */
export const RK_BATCH_02: RkUiTestSpec[] = [
  {
    cardId: "RK-011",
    wikiRef: "docs/wiki/cards/RK-011.md",
    name: "第三の眼",
    kind: "permanent",
    powerCost: 2,
    category: "ET",
    textSnippets: ["※常駐", "カウンター", "無効になる"],
    expectedMechanisms: ["operation_permanent_place", "passive_engine_only"],
    expectedDslKeywords: ["resident"],
  },
  {
    cardId: "RK-012",
    wikiRef: "docs/wiki/cards/RK-012.md",
    name: "宏のオルゴール時計",
    kind: "counter",
    powerCost: 4,
    category: "ET",
    textSnippets: ["※カウンター", "バトルフェイズを飛ばす"],
    expectedMechanisms: ["operation_counter_reaction"],
    expectedDslKeywords: ["counter_skip_battle_phase"],
  },
  {
    cardId: "RK-013",
    wikiRef: "docs/wiki/cards/RK-013.md",
    name: "Jパワー",
    kind: "instant",
    powerCost: 4,
    category: "MA",
    textSnippets: ["Lユニット", "重ねる"],
    expectedMechanisms: ["operation_drag_direct", "effect_choice_modal"],
    expectedDropRoute: "direct_play",
    expectedDslKeywords: ["stack_s_on_self_rush"],
  },
  {
    cardId: "RK-014",
    wikiRef: "docs/wiki/cards/RK-014.md",
    name: "共同戦線",
    kind: "permanent",
    powerCost: 2,
    category: "MA",
    textSnippets: ["※常駐", "警察", "仮面ライダー"],
    expectedMechanisms: ["operation_permanent_place", "passive_engine_only"],
    expectedDslKeywords: ["resident"],
  },
  {
    cardId: "RK-015",
    wikiRef: "docs/wiki/cards/RK-015.md",
    name: "人類の進化",
    kind: "counter",
    powerCost: 3,
    category: "MA",
    textSnippets: ["※カウンター", "仮面ライダー", "ラッシュエリア"],
    expectedMechanisms: ["operation_counter_reaction"],
    expectedDslKeywords: ["counter_recruit_on_destroy"],
  },
  {
    cardId: "RK-016",
    wikiRef: "docs/wiki/cards/RK-016.md",
    name: "ミラーワールド",
    kind: "permanent",
    powerCost: 0,
    category: "WB",
    textSnippets: ["※常駐", "重ねてもよい", "ホールド"],
    expectedMechanisms: ["operation_permanent_place", "passive_engine_only"],
    expectedDslKeywords: ["resident"],
  },
  {
    cardId: "RK-017",
    wikiRef: "docs/wiki/cards/RK-017.md",
    name: "ミッションメモリー",
    kind: "instant",
    powerCost: 2,
    category: "ET",
    textSnippets: ["ＲＣ", "ライドオフ", "ホールド状態"],
    expectedMechanisms: ["operation_drag_direct", "effect_choice_modal"],
    expectedDropRoute: "direct_play",
    expectedDslKeywords: ["rc_hold_skip_rideoff"],
  },
  {
    cardId: "RK-018",
    wikiRef: "docs/wiki/cards/RK-018.md",
    name: "ラウズカード",
    kind: "instant",
    powerCost: 2,
    category: "WB",
    textSnippets: ["ラッシュエリア", "捨札", "BP"],
    expectedMechanisms: ["operation_drag_direct", "effect_choice_modal"],
    expectedDropRoute: "direct_play",
    expectedDslKeywords: ["dual_bp_rush_discard_combine"],
  },
  {
    cardId: "RK-019",
    wikiRef: "docs/wiki/cards/RK-019.md",
    name: "音撃",
    kind: "instant",
    powerCost: 4,
    category: "MA",
    textSnippets: ["メカ", "撃破される"],
    expectedMechanisms: ["operation_drag_direct", "effect_choice_modal"],
    expectedDropRoute: "direct_play",
    expectedDslKeywords: ["impose_destroy_rule_on_enemy"],
  },
  {
    cardId: "RK-020",
    wikiRef: "docs/wiki/cards/RK-020.md",
    name: "ダブルライダーキック",
    kind: "instant",
    powerCost: 6,
    category: "ET",
    textSnippets: ["仮面ライダー", "2体選ぶ", "BP8000"],
    expectedMechanisms: ["operation_drag_direct", "effect_choice_modal"],
    expectedDropRoute: "direct_play",
  },
];
