/**
 * RK/BK grant_keyword 効果の matchedPattern 一覧を生成する。
 *
 * Usage: npx tsx packages/cards/scripts/generate-rkbk-catchall-index.ts
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { rematchExtractedEffect } from "../src/pipeline/extractEffects";
import type { EffectDefinition } from "../src/dsl/types";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dslDir = join(__dirname, "../src/generated/dsl-stubs");
const outPath = join(__dirname, "../../engine/src/rules/rk/rkBkCatchallSpecs.generated.ts");

type Spec = {
  cardId: string;
  effectId: string;
  keyword: string;
  pattern: string;
  text: string;
};

function rematchOptions(effect: EffectDefinition, cardId: string) {
  const text = effect.text ?? "";
  return {
    name: effect.name,
    kind: text.startsWith("※") ? ("note" as const) : effect.name ? ("named" as const) : ("body" as const),
    trigger: effect.trigger,
    cardId,
  };
}

function main(): void {
  const specs: Spec[] = [];

  for (const file of readdirSync(dslDir).filter((f) => /^(RK-|BK-)/.test(f))) {
    const doc = JSON.parse(readFileSync(join(dslDir, file), "utf8")) as {
      id: string;
      effects?: EffectDefinition[];
    };
    for (const effect of doc.effects ?? []) {
      const kw = effect.effects?.find((p) => p.type === "grant_keyword")?.keyword;
      if (!kw) continue;
      const rematched = rematchExtractedEffect(effect.text ?? "", rematchOptions(effect, doc.id));
      specs.push({
        cardId: doc.id,
        effectId: effect.id,
        keyword: kw,
        pattern: rematched?.matchedPattern ?? "unknown",
        text: (effect.text ?? "").slice(0, 200),
      });
    }
  }

  specs.sort((a, b) => a.cardId.localeCompare(b.cardId) || a.effectId.localeCompare(b.effectId));

  const patterns = [...new Set(specs.map((s) => s.pattern))].sort();

  const body = `/** Auto-generated by generate-rkbk-catchall-index.ts — do not edit. */
export type RkBkCatchallSpec = {
  cardId: string;
  effectId: string;
  keyword: string;
  pattern: string;
  text: string;
};

export const RK_BK_CATCHALL_PATTERNS = ${JSON.stringify(patterns, null, 2)} as const;

export const RK_BK_CATCHALL_SPECS: RkBkCatchallSpec[] = ${JSON.stringify(specs, null, 2)};
`;

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, body);
  console.log(`→ ${outPath} (${specs.length} specs, ${patterns.length} patterns)`);
}

main();
