/**
 * 残存 RK catchall を exact-match パターンへ変換する。
 * Usage: npx tsx packages/cards/scripts/generate-rk-exact-patterns.ts
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { rematchExtractedEffect } from "../src/pipeline/extractEffects";
import { isCatchallGrantKeyword } from "../src/pipeline/hashGrantKeywords";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dslDir = join(__dirname, "../src/generated/dsl-stubs");
const outPath = join(__dirname, "../src/pipeline/rkExactPatterns.generated.ts");

function normalizeText(text: string): string {
  return text.replace(/\s+/g, "").trim();
}

function escapeForTsString(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

type CatchallItem = {
  cardId: string;
  effectId: string;
  text: string;
  trigger: unknown;
};

function collectCatchalls(): CatchallItem[] {
  const items: CatchallItem[] = [];
  for (const file of readdirSync(dslDir).sort()) {
    if (!file.startsWith("RK-")) continue;
    const doc = JSON.parse(readFileSync(join(dslDir, file), "utf8"));
    for (const effect of doc.effects ?? []) {
      const stub = effect.effects?.find((p: { type: string }) => p.type === "grant_keyword");
      if (!stub || !isCatchallGrantKeyword(stub.keyword)) continue;
      // セマンティックパターン（exact 以外）で一致する効果文は exact 化しない。
      // エンジンは matchedPattern 単位の解釈（catchallTextPrimitives）を持つため
      // セマンティック一致が優先される（例: RK-126 hand_pick_show_opponent）。
      const rematched = rematchExtractedEffect(effect.text ?? "", {
        trigger: effect.trigger,
        name: effect.name,
        excludeExactPatterns: true,
      });
      if (rematched) continue;
      items.push({
        cardId: doc.id,
        effectId: effect.id,
        text: effect.text ?? "",
        trigger: effect.trigger,
      });
    }
  }
  return items;
}

function main() {
  const items = collectCatchalls();
  const normalizedSet = new Map<string, CatchallItem>();
  for (const item of items) {
    const key = normalizeText(item.text);
    if (!normalizedSet.has(key)) normalizedSet.set(key, item);
  }
  const unique = [...normalizedSet.values()];

  const lines: string[] = [
    "/** Auto-generated by scripts/generate-rk-exact-patterns.ts — do not edit. */",
    'import type { EffectDefinition } from "../dsl/types";',
    'import type { ExtractedEffect, WikiEffectSegment } from "./types";',
    'import { noteEffectIdFromBody, slugifyEffectId } from "./metaMaps";',
    "",
    "type PatternMatch = {",
    '  pattern: string;',
    "  test: (body: string) => boolean;",
    "  build: (",
    "    body: string,",
    "    segment: WikiEffectSegment,",
    "    trigger: EffectDefinition[\"trigger\"],",
    '  ) => Omit<ExtractedEffect, "segmentIndex" | "needsFallback">;',
    "};",
    "",
    "function normalizeBody(body: string): string {",
    '  return body.replace(/\\s+/g, "").trim();',
    "}",
    "",
    "function triggerFromBody(",
    "  body: string,",
    '  fallback: EffectDefinition["trigger"],',
    '): EffectDefinition["trigger"] {',
    '  if (/バトルエリアに出たとき/.test(body)) return { type: "enter_battle" };',
    '  if (/ラッシュしたとき|ラッシュするとき/.test(body)) return { type: "on_rush" };',
    '  if (/アタックしたとき|アタックするとき/.test(body)) return { type: "on_attack" };',
    '  if (/ストライクしたとき|ストライクして/.test(body)) return { type: "on_strike" };',
    '  if (/撃破されて捨札になったとき/.test(body)) return { type: "on_destroy" };',
    '  if (/敵軍ターン中/.test(body) || /にある間/.test(body)) return { type: "while_in_field" };',
    "  return fallback;",
    "}",
    "",
    "function grantRkFx(",
    "  cardId: string,",
    "  effectId: string,",
    "  body: string,",
    "  segment: WikiEffectSegment,",
    "  trigger: EffectDefinition[\"trigger\"],",
    "  matchedPattern: string,",
    "  optional?: boolean,",
    '): Omit<ExtractedEffect, "segmentIndex" | "needsFallback"> {',
    "  return {",
    '    id: segment.name ? slugifyEffectId(segment.name) : noteEffectIdFromBody(body),',
    "    name: segment.name,",
    "    text: body,",
    "    trigger: triggerFromBody(body, trigger),",
    "    optional: optional ?? /してもよい|してよい|選んでもよい/.test(body),",
    "    effects: [",
    "      {",
    '        type: "grant_keyword",',
    '        keyword: `rk_fx::${cardId}::${effectId}`,',
    '        duration: /にある間/.test(body) ? "permanent" : "turn",',
    "      },",
    "    ],",
    "    matchedPattern,",
    "  };",
    "}",
    "",
  ];

  const textConsts: string[] = [];
  const patternEntries: string[] = [];

  unique.forEach((item, index) => {
    const constName = `RK_TEXT_${index}`;
    textConsts.push(`const ${constName} = \`${escapeForTsString(item.text)}\`;`);
    const patternId = `rk_exact_${item.cardId.replace("-", "_")}_${item.effectId.replace(/[^a-zA-Z0-9_]/g, "_")}`;
    patternEntries.push(`  {
    pattern: "${patternId}",
    test: (body) => normalizeBody(body) === normalizeBody(${constName}),
    build: (body, segment, trigger) =>
      grantRkFx("${item.cardId}", "${item.effectId}", body, segment, trigger, "${patternId}"),
  },`);
  });

  lines.push(...textConsts, "", "export const RK_EXACT_PATTERNS: PatternMatch[] = [", ...patternEntries, "];", "");

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join("\n"));
  console.log({ catchallEffects: items.length, uniqueTexts: unique.length, outPath });
}

main();
