/**
 * RS catchall 効果の実装インデックスを生成する。
 *
 * Usage: npx tsx packages/cards/scripts/generate-rs-catchall-index.ts
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { rematchExtractedEffect } from "../src/pipeline/extractEffects";
import { isCatchallGrantKeyword } from "../src/pipeline/hashGrantKeywords";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const dslDir = join(root, "src/generated/dsl-stubs");

type CatchallSpec = {
  cardId: string;
  effectId: string;
  pattern: string;
  keyword: string;
  trigger: string;
  text: string;
};

function collectSpecs(): CatchallSpec[] {
  const specs: CatchallSpec[] = [];
  for (const file of readdirSync(dslDir)) {
    if (!file.startsWith("RS-") || !file.endsWith(".dsl.json")) continue;
    const doc = JSON.parse(readFileSync(join(dslDir, file), "utf8"));
    for (const effect of doc.effects ?? []) {
      const primitives = effect.effects ?? [];
      const grantKeywords = primitives
        .filter((p: { type: string }) => p.type === "grant_keyword")
        .map((p: { keyword: string }) => p.keyword);
      if (!grantKeywords.some(isCatchallGrantKeyword)) continue;
      const rematched = rematchExtractedEffect(effect.text ?? "", {
        name: effect.name,
        kind: (effect.text ?? "").startsWith("※") ? "note" : effect.name ? "named" : "body",
        trigger: effect.trigger,
        cardId: doc.id,
      });
      const structured = rematched?.effects?.some(
        (p) => p.type !== "grant_keyword",
      );
      if (structured) continue;
      specs.push({
        cardId: doc.id,
        effectId: effect.id,
        pattern: rematched?.matchedPattern ?? "unknown",
        keyword: grantKeywords[0]!,
        trigger: effect.trigger?.type ?? "unknown",
        text: effect.text ?? "",
      });
    }
  }
  return specs.sort((a, b) => a.cardId.localeCompare(b.cardId));
}

function main(): void {
  const specs = collectSpecs();
  const keys = specs.map((s) => `${s.cardId}:${s.effectId}`);
  const keywords = [...new Set(specs.map((s) => s.keyword))];
  const cardIds = [...new Set(specs.map((s) => s.cardId))];
  const byPattern: Record<string, number> = {};
  for (const s of specs) {
    byPattern[s.pattern] = (byPattern[s.pattern] ?? 0) + 1;
  }

  const cardsOut = `/** Auto-generated by generate-rs-catchall-index.ts — do not edit. */
export const RS_CATCHALL_EFFECT_KEYS = new Set<string>([
${keys.map((k) => `  ${JSON.stringify(k)},`).join("\n")}
]);

export const RS_CATCHALL_KEYWORDS = new Set<string>([
${keywords.map((k) => `  ${JSON.stringify(k)},`).join("\n")}
]);

export const RS_CATCHALL_CARD_IDS = new Set<string>([
${cardIds.map((k) => `  ${JSON.stringify(k)},`).join("\n")}
]);

export const RS_CATCHALL_SPEC_COUNT = ${specs.length};
`;

  const engineOut = `/** Auto-generated by generate-rs-catchall-index.ts — do not edit. */
export type RsCatchallSpec = {
  cardId: string;
  effectId: string;
  pattern: string;
  keyword: string;
  trigger: string;
  text: string;
};

export const RS_CATCHALL_SPECS: RsCatchallSpec[] = ${JSON.stringify(specs, null, 2)} as RsCatchallSpec[];

export const RS_CATCHALL_BY_CARD: Record<string, RsCatchallSpec[]> = ${JSON.stringify(
    Object.fromEntries(
      cardIds.map((id) => [id, specs.filter((s) => s.cardId === id)]),
    ),
    null,
    2,
  )};
`;

  writeFileSync(join(root, "src/rsCatchallImplemented.ts"), `${cardsOut}\n`);
  mkdirSync(join(root, "../../packages/engine/src/rules/rs"), { recursive: true });
  writeFileSync(
    join(root, "../../packages/engine/src/rules/rs/rsCatchallSpecs.generated.ts"),
    `${engineOut}\n`,
  );

  console.log(
    JSON.stringify(
      {
        specs: specs.length,
        cards: cardIds.length,
        keywords: keywords.length,
        byPattern,
      },
      null,
      2,
    ),
  );
}

main();
