/**
 * RM/PR 残存 catchall を exact-match パターンへ変換する。
 * Usage: npx tsx packages/cards/scripts/generate-promoted-exact-patterns.ts
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { rematchExtractedEffect } from "../src/pipeline/extractEffects";
import { isCatchallGrantKeyword } from "../src/pipeline/hashGrantKeywords";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dslDir = join(__dirname, "../src/generated/dsl-stubs");

type PrefixConfig = {
  prefix: string;
  fxNamespace: "rm" | "pr";
  outFile: string;
  exportName: string;
  grantFn: string;
};

const PREFIX_CONFIGS: PrefixConfig[] = [
  {
    prefix: "RM-",
    fxNamespace: "rm",
    outFile: "rmExactPatterns.generated.ts",
    exportName: "RM_EXACT_PATTERNS",
    grantFn: "grantRmFx",
  },
  {
    prefix: "PR-",
    fxNamespace: "pr",
    outFile: "prExactPatterns.generated.ts",
    exportName: "PR_EXACT_PATTERNS",
    grantFn: "grantPrFx",
  },
];

function normalizeText(text: string): string {
  return text.replace(/\s+/g, "").trim();
}

function escapeForTsString(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

type CatchallItem = {
  cardId: string;
  effectId: string;
  text: string;
};

function collectFromStableFx(cardPrefix: string, fxNamespace: string): CatchallItem[] {
  const items: CatchallItem[] = [];
  for (const file of readdirSync(dslDir).sort()) {
    if (!file.startsWith(cardPrefix)) continue;
    const doc = JSON.parse(readFileSync(join(dslDir, file), "utf8"));
    for (const effect of doc.effects ?? []) {
      const stub = effect.effects?.find((p: { type: string }) => p.type === "grant_keyword");
      const kw = stub?.keyword as string | undefined;
      if (!kw?.startsWith(`${fxNamespace}_fx::`)) continue;
      items.push({
        cardId: doc.id,
        effectId: effect.id,
        text: effect.text ?? "",
      });
    }
  }
  return items;
}

function collectCatchalls(cardPrefix: string, fxNamespace: string): CatchallItem[] {
  const items: CatchallItem[] = [];
  for (const file of readdirSync(dslDir).sort()) {
    if (!file.startsWith(cardPrefix)) continue;
    const doc = JSON.parse(readFileSync(join(dslDir, file), "utf8"));
    for (const effect of doc.effects ?? []) {
      const stub = effect.effects?.find((p: { type: string }) => p.type === "grant_keyword");
      if (!stub || !isCatchallGrantKeyword(stub.keyword)) continue;
      const rematched = rematchExtractedEffect(effect.text ?? "", {
        trigger: effect.trigger,
        name: effect.name,
      });
      const stillCatchall = rematched?.effects.some(
        (p) => p.type === "grant_keyword" && isCatchallGrantKeyword(p.keyword),
      );
      if (!stillCatchall) continue;
      items.push({
        cardId: doc.id,
        effectId: effect.id,
        text: effect.text ?? "",
      });
    }
  }
  const merged = new Map<string, CatchallItem>();
  for (const item of [...items, ...collectFromStableFx(cardPrefix, fxNamespace)]) {
    merged.set(`${item.cardId}::${item.effectId}`, item);
  }
  return [...merged.values()];
}

function buildFile(config: PrefixConfig, items: CatchallItem[]): void {
  const normalizedSet = new Map<string, CatchallItem>();
  for (const item of items) {
    const key = normalizeText(item.text);
    if (!normalizedSet.has(key)) normalizedSet.set(key, item);
  }
  const unique = [...normalizedSet.values()];
  const ns = config.fxNamespace;

  const lines: string[] = [
    `/** Auto-generated by scripts/generate-promoted-exact-patterns.ts — do not edit. */`,
    'import type { EffectDefinition } from "../dsl/types";',
    'import type { ExtractedEffect, WikiEffectSegment } from "./types";',
    'import { noteEffectIdFromBody, slugifyEffectId } from "./metaMaps";',
    "",
    "type PatternMatch = {",
    '  pattern: string;',
    "  test: (body: string) => boolean;",
    "  build: (",
    "    body: string,",
    "    segment: WikiEffectSegment,",
    "    trigger: EffectDefinition[\"trigger\"],",
    '  ) => Omit<ExtractedEffect, "segmentIndex" | "needsFallback">;',
    "};",
    "",
    "function normalizeBody(body: string): string {",
    '  return body.replace(/\\s+/g, "").trim();',
    "}",
    "",
    "function triggerFromBody(",
    "  body: string,",
    '  fallback: EffectDefinition["trigger"],',
    '): EffectDefinition["trigger"] {',
    '  if (/バトルエリアに出たとき/.test(body)) return { type: "enter_battle" };',
    '  if (/ラッシュしたとき|ラッシュするとき/.test(body)) return { type: "on_rush" };',
    '  if (/アタックしたとき|アタックするとき/.test(body)) return { type: "on_attack" };',
    '  if (/ストライクしたとき|ストライクして/.test(body)) return { type: "on_strike" };',
    '  if (/撃破されて捨札になったとき/.test(body)) return { type: "on_destroy" };',
    '  if (/敵軍ターン中/.test(body) || /にある間/.test(body)) return { type: "while_in_field" };',
    "  return fallback;",
    "}",
    "",
    `function ${config.grantFn}(`,
    "  cardId: string,",
    "  effectId: string,",
    "  body: string,",
    "  segment: WikiEffectSegment,",
    "  trigger: EffectDefinition[\"trigger\"],",
    "  matchedPattern: string,",
    "  optional?: boolean,",
    '): Omit<ExtractedEffect, "segmentIndex" | "needsFallback"> {',
    "  return {",
    '    id: segment.name ? slugifyEffectId(segment.name) : noteEffectIdFromBody(body),',
    "    name: segment.name,",
    "    text: body,",
    "    trigger: triggerFromBody(body, trigger),",
    "    optional: optional ?? /してもよい|してよい|選んでもよい/.test(body),",
    "    effects: [",
    "      {",
    '        type: "grant_keyword",',
    `        keyword: \`${ns}_fx::\${cardId}::\${effectId}\`,`,
    '        duration: /にある間/.test(body) ? "permanent" : "turn",',
    "      },",
    "    ],",
    "    matchedPattern,",
    "  };",
    "}",
    "",
  ];

  const textConsts: string[] = [];
  const patternEntries: string[] = [];

  unique.forEach((item, index) => {
    const constName = `${ns.toUpperCase()}_TEXT_${index}`;
    textConsts.push(`const ${constName} = \`${escapeForTsString(item.text)}\`;`);
    const patternId = `${ns}_exact_${item.cardId.replace("-", "_")}_${item.effectId.replace(/[^a-zA-Z0-9_]/g, "_")}`;
    patternEntries.push(`  {
    pattern: "${patternId}",
    test: (body) => normalizeBody(body) === normalizeBody(${constName}),
    build: (body, segment, trigger) =>
      ${config.grantFn}("${item.cardId}", "${item.effectId}", body, segment, trigger, "${patternId}"),
  },`);
  });

  lines.push(...textConsts, "", `export const ${config.exportName}: PatternMatch[] = [`, ...patternEntries, "];", "");

  const outPath = join(__dirname, "../src/pipeline", config.outFile);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join("\n"));
  console.log({
    prefix: config.prefix,
    catchallEffects: items.length,
    uniqueTexts: unique.length,
    outPath,
  });
}

function main() {
  for (const config of PREFIX_CONFIGS) {
    buildFile(config, collectCatchalls(config.prefix, config.fxNamespace));
  }
}

main();
